Add arm-linux-gnueabi-gcc build
ARMmbed/mbedtls pull request #3572
Opened 2020-08-18 08:42 UTC by mpg

## Description

Add a build with arm-linux-gnueabi-gcc - compared to existing Arm builds, this allows building the programs and tests, in order to catch platform-dependent issues there too (previously we only cross-built the library to Arm).

See https://github.com/ARMmbed/mbedtls/pull/3449#issuecomment-675313720

See also. https://github.com/ARMmbed/mbedtls/issues/3299

## Status
**READY**

## Requires Backporting
Yes - testing improvement 

- [ ] 2.16
- [ ] 2.7

## Additional comments

The newly added test on Travis is expected to fail until #3449 is merged.

2020-08-18 08:50 UTC, hanno-arm commented
Thanks @mpg for this PR! Can we go one step further and use QEMU and syscall emulation to actually run our test suites? I've done this locally lately and it didn't require any change to the test scripts - once the tooling is setup correctly, the system will detect the target architecture for binaries automatically and transparently hook in QEMU.

2020-08-18 09:05 UTC, mpg commented
Yes, sure, that would be a great improvement! But I'd rather take an incremental approach and add qemu in a follow-up PR - feel free to submit one if you already have something working locally.

(Also, I'm not sure if you're aware, but at the moment we can't easily update the Docker images used by our Jenkins CI, there are a couple of things we need to address before we can do that again, see https://github.com/ARMmbed/mbedtls-test/issues/150 - so for now we can only install additional software on Travis.)

2020-08-18 09:09 UTC, hanno-arm commented
@mpg Ok, let's leave it to another PR.

> (Also, I'm not sure if you're aware, but at the moment we can't easily update the Docker images used by our Jenkins CI, there are a couple of things we need to address before we can do that again, see ARMmbed/mbedtls-test#150 - so for now we can only install additional software on Travis.)

Yes, @dgreen-arm told me about it, and that was the reason I didn't pursue adding Arm tests to the CI anymore (my main interest is getting tests for #1424), but I overlooked Travis, which is also a good start.

2020-09-02 10:46 UTC, mpg commented
The CI is failing because Jenkins has a check to make sure it can run all the components, which makes sense, but prevents us from merging this PR before we've updated the Docker images, so this PR also depends on https://github.com/ARMmbed/mbedtls-test/issues/150

2021-07-05 07:37 UTC, ronald-cron-arm requested changes
This looks overall good to me. I have two minor comments and this needs to be rebased.

2021-07-05 07:37 UTC, ronald-cron-arm commented on tests/scripts/all.sh
> +    # component_build_arm_none_eabi_gcc_arm5vte
```suggestion
    # component_build_arm_linux_gnueabi_gcc_arm5vte
```

2021-07-05 08:18 UTC, mpg commented
@ronald-cron-arm Thanks for your review! I've rebased to resolve the conflicts, and applied the suggested fix in the original commit since I was rebasing anyway.

2021-07-05 09:55 UTC, ronald-cron-arm commented
From the CI it seems that the check to run `build_arm_linux_gnueabi_gcc_arm5vte` only if the `gcc-arm-llinux-gnueabi` is installed does not work.

2021-07-06 07:40 UTC, mpg commented
> From the CI it seems that the check to run `build_arm_linux_gnueabi_gcc_arm5vte` only if the `gcc-arm-llinux-gnueabi` is installed does not work.

Jenkins correctly reports "Unable to run all.sh components: build_arm_linux_gnueabi_gcc_arm5vte", so I think the check works and the Jenkins job notices it can't run this component (as opposed to trying to run it and then failing) but it was also designed to not silently skip components it can't run and fail instead. I think that part is fully expected as long as we haven't installed the toolchain in our Docker image (which is why this PR was stalled).

I'm more worried about the failure in Travis, apparently our install is not complete. (The test passes on my machine, so I must have the right package but now I need to identify which one it is.)

2021-07-06 08:21 UTC, mpg commented
OK, Travis is passing now. Now we're waiting for https://github.com/ARMmbed/mbedtls-test/issues/165 to update the Docker image.

2021-07-06 11:33 UTC, ronald-cron-arm commented
> Jenkins correctly reports "Unable to run all.sh components: build_arm_linux_gnueabi_gcc_arm5vte", so I think the check works and the Jenkins job notices it can't run this component (as opposed to trying to run it and then failing) but it was also designed to not silently skip components it can't run and fail instead. I think that part is fully expected as long as we haven't installed the toolchain in our Docker image (which is why this PR was stalled).

ok thanks for the explanation.

2021-07-06 11:39 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM

2021-07-30 19:03 UTC, gilles-peskine-arm approved these changes

2021-08-02 07:35 UTC, mpg commented
Do you mind if I rebase this on recent development? This would avoid the distracting failure of the API/ABI checker.

2021-08-02 08:50 UTC, gilles-peskine-arm commented
Please go ahead and rebase.

2021-08-03 11:51 UTC, gilles-peskine-arm approved these changes
Re-approving after rebase.

Now that the necessary compiler is present on Jenkins, I have verified that the PR job ran it as expected.

2021-08-12 10:15 UTC, mstarzyk-mobica approved these changes

2021-08-12 10:20 UTC, lukgni approved these changes

2021-08-12 11:16 UTC, merged