Backport 2.7: Fix compat.sh with ubuntu 16.04 gnutls 2.7
ARMmbed/mbedtls pull request #3594
Opened 2020-08-21 17:29 UTC by gilles-peskine-arm

Fix https://github.com/ARMmbed/mbedtls/issues/3520 (travis build) for 2.7. Backport of https://github.com/ARMmbed/mbedtls/pull/3590.

2.7 required more work due to a limitation in older versions of GnuTLS including our default one (3.4.10) but not the one we use as `GNUTLS_NEXT` (3.6.5): it compares distinguished names by their representation, so a `PrintableString` cannot be equal to a `UTF8String`. In 
https://github.com/ARMmbed/mbedtls/pull/1641 we patched some of our code and test data to cope with this limitation. In https://github.com/ARMmbed/mbedtls/pull/2418 we made a partial backport of the test data patches, but we didn't update the SHA-256 client certificate. This PR updates the whole `tests/data_files/cert_${hash}.crt` family to have `PrintableString` DN for the issuer.

The commit “cert_write: support all hash algorithms” is included here because it was necessary to regenerate the certificates. I made a separate PR for some other minor things that I stumbled on while working on this: https://github.com/ARMmbed/mbedtls/pull/3597.

2020-08-24 07:23 UTC, mpg approved these changes
Looks good to me. Thanks for investigating.

2020-08-24 08:51 UTC, hanno-arm commented on programs/x509/cert_write.c
> +            const mbedtls_md_info_t *md_info =
:+1:

2020-08-24 08:58 UTC, hanno-arm requested changes
`library/certs.c` needs to be updated to contain the new `server2-sha256.crt` certificate. You might want to use #2596 for that. Other than that, the PR looks good to me.

2020-08-24 09:01 UTC, hanno-arm commented
@gilles-peskine-arm @mpg https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.7/library/certs.c#L207 suggests that `library/certs.c` shouldn't be updated for ABI stability. What do you think?

2020-08-24 11:16 UTC, mpg approved these changes
LGTM

2020-08-24 12:54 UTC, hanno-arm approved these changes

2020-08-24 14:12 UTC, gilles-peskine-arm commented
I rewrote the last commit because I'd accidentally committed a test version of `certs.c` with a changed size for `mbedtls_test_srv_crt_rsa`, instead of the version that I intended.

Regarding the conundrum of changing the certificate size vs keeping the file in `data_files` distinct from `certs.c`, this turned out not to be an issue because `certs.c` already had a different version as `data_files`, and the old version in `certs.c` had the same size as the new version in `data_files`. (Summarized from a chat discussion, and explained in the commit message.)

2020-08-25 07:02 UTC, mpg approved these changes
LGTM

2020-08-25 07:59 UTC, hanno-arm approved these changes

2020-08-25 08:00 UTC, merged