Backport 2.7: Support building on e2k (Elbrus) architecture
ARMmbed/mbedtls pull request #3599
Opened 2020-08-22 21:50 UTC by makise-homura

Backport of https://github.com/ARMmbed/mbedtls/pull/3574

Signed-off-by: makise-homura <akemi_homura@kurisa.ch>

## Description
This pull request introduces support for building mbedtls 2.7 on Elbrus hardware platform (which is based on Russian [Elbrus](https://en.wikipedia.org/wiki/Elbrus-8S) CPU family) with its native lcc (eLbrus Compiler Collection) compiler.

## Status
**READY**

## Requires Backporting
This is actually a backport.

## Migrations
NO

## Additional comments
This PR fixes the issues causing `-Wsigned-one-bit-field` and `-Wsign-compare` warnings, and probably incorrect execution flow of `dh_genprime`.

Suggested in PR #3574 discussion.

## Todos
- [x] Changelog updated

## Steps to test or reproduce
To reproduce, you should have an Elbrus workstation with OS Elbrus >= 5.0-rc2 and CPU which is Elbrus-8C (Elbrus-8S) or newer (you may ask contributor for SSH access to demo station).
Building with `mkdir build; cd build; cmake .. && make -j16` should succeed and produce no warnings.

2020-08-24 08:10 UTC, gilles-peskine-arm approved these changes

2020-08-24 08:43 UTC, hanno-arm requested changes
As in the original #3574, the bounds check isn't right and should be `ret > (int) SIZE_MAX` instead of `(size_t) ret > SIZE_MAX`, which is vacuous.

2020-08-24 15:40 UTC, makise-homura commented
The issue same as in PR #3574, was fixed in 329fe7e.

2020-08-25 07:17 UTC, gilles-peskine-arm approved these changes

2020-08-25 07:34 UTC, hanno-arm approved these changes

2020-08-25 07:46 UTC, merged