[Backport 2.16] NetBSD symbol availability fix
ARMmbed/mbedtls pull request #3602
Opened 2020-08-23 21:48 UTC by gufe44

This is a backport of #3571.

2020-10-06 14:42 UTC, daverodgman approved these changes
LGTM

2020-10-13 19:43 UTC, gilles-peskine-arm requested changes
As in https://github.com/ARMmbed/mbedtls/pull/3656#discussion_r504208164: `_xxx_SOURCE` should not be redefined if it's already defined.

2020-10-30 19:44 UTC, gufe44 commented
Unfortunately, for personal reasons I won't be able to continue to work on the PR. You can close the PR now and resurrect the branch at any time.

2020-11-12 10:40 UTC, gilles-peskine-arm approved these changes

2020-11-12 11:12 UTC, merged