Use RDTICK instead of RDPR on sparc64 platforms
ARMmbed/mbedtls pull request #3620
Opened 2020-08-29 08:33 UTC by gufe44

Apparently OpenBSD _does_ allow reads from the TICK register, The RDPR instruction is only available to privileged software however so this could not work on any operating system (nonprivileged software must use the RDTICK instruction instead).

2020-09-03 20:47 UTC, niacat commented
I don't understand why `CLOCK_MONOTONIC` isn't used directly on NetBSD? TSC is unreliable on a bunch of systems, it's much better to let the kernel pick the most reasonable option from the range of sources it supports (or indeed the user with `sysctl kern.timecounter.`)

2020-09-07 15:45 UTC, bensze01 commented
The CI is complaining of the following errors:

```
timing.c:66:21: error: field ‘start’ has incomplete type
     struct timespec start;
                     ^
timing.c: In function ‘mbedtls_timing_get_timer’:
timing.c:353:9: error: implicit declaration of function ‘clock_gettime’ [-Werror=implicit-function-declaration]
         clock_gettime( CLOCK_MONOTONIC, &t->start );
         ^
timing.c:353:24: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
         clock_gettime( CLOCK_MONOTONIC, &t->start );
                        ^
timing.c:353:24: note: each undeclared identifier is reported only once for each function it appears in
timing.c:363:25: error: storage size of ‘now’ isn’t known
         struct timespec now;
                         ^
timing.c:363:25: error: unused variable ‘now’ [-Werror=unused-variable]
cc1: all warnings being treated as errors
Makefile:263: recipe for target 'timing.o' failed
make[1]: *** [timing.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:17: recipe for target 'lib' failed
make: *** [lib] Error 2
^^^^test_gcc_opt: build/test: gcc -Os, full config: command make CC=gcc CFLAGS=-Os -std=c99 -pedantic -Wall -Wextra -Werror -> 2^^^^
(skipped because the build failed)
```

Full log: https://gist.github.com/bensze01/da8b24a393eebfd0066722cd30eb84e8

2020-09-07 16:01 UTC, bensze01 requested changes

2020-09-09 17:58 UTC, gufe44 commented
Thank you for pointing out the problems with _POSIX_TIMERS and _POSIX_MONOTONIC_CLOCK. I have taken a look on Debian, Solaris, NetBSD, OpenBSD and FreeBSD. Monotonic time is available on all of them but Debian sets _POSIX_MONOTONIC_CLOCK to 0 and OpenBSD (like macOS) sets _POSIX_TIMERS to -1. I concluded to implement runtime checks. The CI error was due to -std=c99 without defining _POSIX_C_SOURCE.

2020-09-28 09:43 UTC, bensze01 requested changes

2020-09-28 09:43 UTC, bensze01 commented on library/timing.c
> +#define _POSIX_C_SOURCE 200112L
[FreeBSD doesn't define `gettimeofday()` if only `_POSIX_C_SOURCE `is defined, without `_XOPEN_SOURCE`.](https://github.com/freebsd/freebsd/blob/release/11.1.0/sys/sys/time.h#L494)

See relevant failed build log [here](https://gist.github.com/bensze01/870cb75042140eb235962beb590dd6cf) (please ignore the warnings about `static_assert`).

`_XOPEN_SOURCE >= 600` also [implies `_POSIX_C_SOURCE 200112L`](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html).
```suggestion
/*
 * for clock_gettime() from <time.h>
 * and for gettimeofday() from <sys/time.h> on FreeBSD
 */
#define _XOPEN_SOURCE 600
```

2020-10-06 10:16 UTC, gufe44 commented
@niacat Could you clarify what your suggested change is?

2020-10-30 19:44 UTC, gufe44 commented
Unfortunately, for personal reasons I won't be able to continue to work on the PR. You can close the PR now and resurrect the branch at any time.

2020-11-09 09:42 UTC, closed without merging