_POSIX_C_SOURCE fixes
ARMmbed/mbedtls pull request #3645
Opened 2020-09-03 17:50 UTC by gufe44

This is a work in progress intended to addres several issues concerning the use of the _POSIX_C_SOURCE macro:

- POSIX version number typo in platform_util.c and threading.c
- There exists another issue in the same files: comparison `_POSIX_VERSION >= 200809L` after version 200112L was requested
- Make use of the _POSIX_C_SOURCE macro more consistent across all occurences by removing unnecessary conditionals and moving definitions from makefiles to source files. Rationale: make source files more self contained; document individual uses; address platform differences should the need arise, for example:
- Solaris 10 forces an error in feature_tests.h if C99 and a POSIX version other than 200112L are used or 200112L is used without C99. The same problem exists on Solaris 11 with gcc binary packages from OpenCSW. Currently LTS branch 2.16 uses `#define _POSIX_C_SOURCE 1` which is intended to be consistent with the (mostly) C89/GNU89 code. Since the branch also builds with C99, this could hint at a possible portability tradeoff vs. `#define _POSIX_C_SOURCE 200112L` ([#3420](https://github.com/ARMmbed/mbedtls/issues/3420), [#3421](https://github.com/ARMmbed/mbedtls/pull/3421))

Any help would be appreciated. In particular I would like to document but am still unsure about:

- Why 200809L in particular is requested in tests/Makefile and tests/CMakeLists.txt
- If gmtime_r is supposed to be optional or required for POSIX.1-2001

2020-10-30 19:44 UTC, gufe44 commented
Unfortunately, for personal reasons I won't be able to continue to work on the PR. You can close the PR now and resurrect the branch at any time.

2020-11-12 17:36 UTC, chris-jones-arm requested changes
These changes are clearly a work in progress and do not address all of the issues mentioned. That being said the typo fixes are welcome and have been added as part of #3877.

2020-11-12 17:41 UTC, chris-jones-arm commented
These changes have been incorporated into #3877 and this PR can be closed for now. 

Thank you @gufe44 for your contribution.

2020-11-12 17:41 UTC, closed without merging

2020-11-17 12:50 UTC, chris-jones-arm commented
As these changes have been incorporated into #3877 this PR can be closed for now. 

Thank you @gufe44 for your contribution.