Allow builds with -std=c99 on LTS branch 2.7
ARMmbed/mbedtls pull request #3656
Opened 2020-09-09 10:00 UTC by gufe44

Includes (partial) backports of #1198, #3190, #3421, #3422 and #3571.

2020-10-08 08:31 UTC, daverodgman requested changes

2020-10-08 08:31 UTC, daverodgman commented on tests/suites/main_test.function
> +                                {
It would be simpler to call strncpy here

2020-10-08 15:16 UTC, daverodgman approved these changes

2020-10-13 19:42 UTC, gilles-peskine-arm requested changes
The changes are ok, except that the `_xxx_SOURCE` macros should only be defined if they aren't already defined.

Please add `-std=c99 -pedantic` to [`test_build_opt` in `all.sh`](https://github.com/ARMmbed/mbedtls/blob/v2.24.0/tests/scripts/all.sh#L1673), as is already the case in `mbedtls-2.16` and `development`, to avoid future regressions.

2020-10-13 19:42 UTC, gilles-peskine-arm commented on library/entropy_poll.c
> +#define _GNU_SOURCE
As reported in https://github.com/ARMmbed/mbedtls/issues/3432, `_GNU_SOURCE` should not be redefined if it's already defined.

This also applies to `_POSIX_C_SOURCE`, `_XOPEN_SOURCE` and any similar macro.

2020-10-30 19:44 UTC, gufe44 commented
Unfortunately, for personal reasons I won't be able to continue to work on the PR. You can close the PR now and resurrect the branch at any time.

2020-11-12 11:19 UTC, gilles-peskine-arm requested changes
As with https://github.com/ARMmbed/mbedtls/pull/3658#pullrequestreview-528987682, I don't think these changes are correct, because they require a more recent POSIX version than what the long-time-support branch originally required.

2020-11-12 15:15 UTC, chris-jones-arm commented
I agree with the above. This is being closed as these changes would not be compatible with older systems on the LTS.

2020-11-12 15:15 UTC, closed without merging