entropy: Adding brackets inside if/else
ARMmbed/mbedtls pull request #3699
Opened 2020-09-22 09:11 UTC by thopiekar

I tried to compile mbedtls while defining:

#define MBEDTLS_PLATFORM_PRINTF_MACRO MY_PRETTY_PRINTF

in my mbedtls_config.h. However, the compiler got confused at this point because of the missing brackets and expected something additional.
Adding these brackets, even if normally unnessesary, made my compiler get to calm again and guess that might be helpful for other people out there, too.
I believe the reason is simply that I defined:

#define MY_PRETTY_PRINTF(...) printlog(__VA_ARGS__);

So, the line, eg. `mbedtls_printf( "passed\n" );` will look like: `printlog( "passed\n" );;`, which is interpreted as two function calls since two semicolons are there.

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2020-09-22 13:30 UTC, ronald-cron-arm commented
Why not just defining your macro without the final ";":
#define MY_PRETTY_PRINTF(...) printlog(__VA_ARGS__)

2020-09-22 14:28 UTC, thopiekar commented
Yeah, that would be the easiest. But I think the benefit is still that you can also place multiple functions into your define. E.g. two printf's where one prints to your serial and the other into a file on your SD card.
Again, you can define another function which bundles both into one function, but nevertheless I find it beneficial to have freedom around defines. That's what they are mostly for, in my point of view. :smiley:

2020-09-24 08:51 UTC, ronald-cron-arm commented
The project's configuration allows you to define the "mbedtls_printf" function pointer. The constraint is that it is a function pointer but not necessary a direct pointer to one of the log functions of your platforms. If you need to output the logs to different ports you can wrap the log calls in one platform function and define "mbedtls_printf" to point to that function.
Thus from what we said so far, I don't see really see the benefit of this. It seems to me that the use cases you mentioned can be addressed by the library without this change.

2020-09-24 12:52 UTC, gilles-peskine-arm commented
`MBEDTLS_PLATFORM_STD_PRINTF` is documented as a macro that expands to a function name. Although we don't currently do it,
```
fptr = &MBEDTLS_PLATFORM_PRINTF_MACRO;
```
would be valid code. So defining `MBEDTLS_PLATFORM_PRINTF_MACRO` as a macro with arguments is wrong, and may fail in a future version of Mbed TLS (although that's unlikely). Defining `MBEDTLS_PLATFORM_PRINTF_MACRO` as a macro with an argument that expands to something that is not an expression is definitely wrong.

As a general note, in C, a macro that expands to something that ends with a semicolon is almost always wrong. [The standard idiom for a macro that expands to a statement is `do { … } while (0)`](https://stackoverflow.com/questions/257418/do-while-0-what-is-it-good-for).

2020-09-24 12:53 UTC, gilles-peskine-arm requested changes
While this change isn't _wrong_ in itself, it's unnecessary. It also has the side-effect of silencing a configuration error, so applying it would be detrimental to the library.

2020-09-30 13:30 UTC, ronald-cron-arm commented
The changes in this PR in how "mbedtls_printf()" was called in entropy.c were made necessary by the way the MBEDTLS_PLATFORM_PRINTF_MACRO was defined. As we pointed out the macro is aimed to just expand to a function name. Furthermore, we think that the use cases you mentioned (like two different log outputs) can be well served by MBEDTLS_PLATFORM_PRINTF_MACRO just expending to a function name. Thus, closing this PR. Thanks for your interest in Mbed TLS.

2020-09-30 13:30 UTC, closed without merging