Fix PSA crypto inconsistencies in agreement+derivation
ARMmbed/mbedtls pull request #3743
Opened 2020-10-02 20:12 UTC by stevew817

## Description
Fix #3741: Allow key agreement inside derivation with a key that's allowed for the relevant agreement.
Fix #3742: After input of a key as SECRET in the derivation, allow the derivation result to be used as key.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Additional comments
Is a changelog needed?

## Todos
- [X] Tests
- [ ] Changelog updated

## Steps to test or reproduce
Unit tests.

2020-10-02 20:53 UTC, gilles-peskine-arm commented
These are two separate changes. They're small enough to put in the same pull request, but please make separate commits.

Yes, please add changelog entries (one Bugfix and one Features).

2020-10-05 14:24 UTC, stevew817 commented
@gilles-peskine-arm split in two commits and added changelog entries. Ready for review.

2020-10-09 06:44 UTC, ronald-cron-arm requested changes
Looks overall good to me. I have a few suggestions for improvement. I've checked that the unit tests that are supposed to fail when the corresponding changes to psa_crypto.c are reverted actually fail.

2020-10-15 13:30 UTC, stevew817 commented on library/psa_crypto.c
> +    if( step == PSA_KEY_DERIVATION_INPUT_SECRET )
Sure.

2020-10-15 15:07 UTC, stevew817 commented
@ronald-cron-arm all your feedback is now applied.

2020-10-16 06:29 UTC, ronald-cron-arm approved these changes
Thanks for the changes. It looks good to me now.

2020-10-20 16:16 UTC, paul-elliott-arm approved these changes
Looks good to me with latest changes.

2020-10-21 11:25 UTC, merged