Reduce ROM usage due to X.509 info
ARMmbed/mbedtls pull request #3777
Opened 2020-10-09 10:22 UTC by hanno-arm

This is a rebase and rework of #2315. Many thanks to @pkolbus for the initial contribution!

2020-12-15 12:44 UTC, chris-jones-arm requested changes
I think this is almost there it mostly just needs cleaning up, rebasing and then to fix the CI error which looks like some tests are failing because it's expecting some X.509 info output which it isn't getting.

I will investigate further and I'd be happy to make any final changes myself as necessary.

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/cert_app.c
> +    !!defined(MBEDTLS_X509_REMOVE_INFO) || !defined(MBEDTLS_CTR_DRBG_C)
I think this would be clearer without the double negation (`!!defined` == `defined`).

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/cert_app.c
> +           "MBEDTLS_X509_REMOVE_INFO and/or MBEDTLS_CTR_DRBG_C not defined.\n");
This should be `"MBEDTLS_X509_REMOVE_INFO defined and/or MBEDTLS_CTR_DRBG_C not defined.\n"` to match the prior preprocessor guard.

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/crl_app.c
> +    !!defined(MBEDTLS_X509_REMOVE_INFO)
I think this would be clearer without the double negation (`!!defined` == `defined`).

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/crl_app.c
> +           "MBEDTLS_X509_REMOVE_INFO not defined.\n");
This should be `"MBEDTLS_X509_REMOVE_INFO defined.\n"` to match the prior preprocessor guard.

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/req_app.c
> +    !!defined(MBEDTLS_X509_REMOVE_INFO)
I think this would be clearer without the double negation (`!!defined` == `defined`).

2020-12-15 12:44 UTC, chris-jones-arm commented on programs/x509/req_app.c
> +           "MBEDTLS_X509_REMOVE_INFO not defined.\n");
This should be `"MBEDTLS_X509_REMOVE_INFO defined.\n"` to match the prior preprocessor guard.

2020-12-15 12:44 UTC, chris-jones-arm commented on tests/suites/test_suite_x509parse.function
> +
Minor: remove extra newline.

2020-12-15 12:44 UTC, chris-jones-arm commented on tests/suites/test_suite_x509parse.function
> +
Minor: remove extra newline.

2020-12-16 09:25 UTC, chris-jones-arm commented on include/mbedtls/config.h
> +#define MBEDTLS_X509_REMOVE_INFO
Having this definition uncommented by default may also be what is causing the CI to fail as it is failing when running a test on the default config and then using `grep` to look for output which won't be there. I have partially tested this and the test does pass when this line is commented in the default config.

2020-12-16 16:46 UTC, chris-jones-arm commented
Rebased to add missing sign-offs and fix merge conflicts.

2020-12-16 17:31 UTC, chris-jones-arm commented
Rebased again to fix another incorrect signoff, which caused the DCO check to fail, on a74571c.

2020-12-17 11:54 UTC, chris-jones-arm commented
Hi @pkolbus, we have found that one of your original commits (a74571c) does not have a DCO sign-off attached. This is understandable as when you originally made the commit we were using a CLA, which you signed.

As we have replaced the CLA with a DCO, we just wanted to check with you to make sure are happy for your commit to use a DCO instead.

2020-12-17 14:52 UTC, chris-jones-arm approved these changes

2020-12-17 15:15 UTC, chris-jones-arm commented
As I have contributed to this PR, two more reviews/approvals are needed.

2020-12-17 15:33 UTC, chris-jones-arm commented on tests/suites/test_suite_x509parse.function
>      mbedtls_x509_buf oid;
Because the original author (@pkolbus) signed a CLA when this commit was first made, a DCO from the original author is not needed

2021-04-09 18:46 UTC, gilles-peskine-arm commented
FYI there's a merge conflict.

2021-04-27 15:42 UTC, tom-daubney-arm approved these changes
After going through this PR I am happy that these changes can now be rebased onto the latest.
LGTM.

2021-04-27 17:04 UTC, paul-elliott-arm approved these changes
Looks fine to me, CI willing.

2021-04-28 07:37 UTC, tom-daubney-arm approved these changes
LGTM

2021-04-28 14:03 UTC, paul-elliott-arm approved these changes
LGTM

2021-04-28 14:23 UTC, tom-daubney-arm approved these changes
LGTM.

2021-04-28 16:31 UTC, merged