Fix: Add missing arguments to debug message.
ARMmbed/mbedtls pull request #3930
Opened 2020-12-01 11:16 UTC by ccvca

## Description
Add missing values for a debug message in mbedtls_ssl_decrypt_buf

Found by [CodeQL](https://securitylab.github.com/tools/codeql):

## Status
**READY**

## Requires Backporting
Yes (?), as this bug might leak 8 arbitrary bytes to the (debug) console.

## Migrations
NO

## Additional comments

## Todos
- [ ] Tests
- [x] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce

2020-12-01 19:03 UTC, paul-elliott-arm submitted a review, later dismissed
Looks correct to me - can you please do backports?

2020-12-01 20:40 UTC, gilles-peskine-arm requested changes
Looks good to me except that the changelog entry isn't a proper text file (which is why the CI is unhappy).

2020-12-01 20:40 UTC, gilles-peskine-arm commented on ChangeLog.d/missing-debug-message-arguments_mbedtls_ssl_decrypt_buf.txt
> +  * Add missing arguments of debug message in mbedtls_ssl_decrypt_buf
Please add a line break character at the end of the line.

2020-12-02 06:23 UTC, ccvca commented
I've fixed the line break.
Other than expected first, this does not require a backport, as it was introduced only 7 months ago and is not part in 2.16 or 2.7 (at least I can't find it)

2020-12-02 08:53 UTC, gilles-peskine-arm commented on ChangeLog.d/missing-debug-message-arguments_mbedtls_ssl_decrypt_buf.txt
> +Bugfix:
Sorry, CI is still not happy:
```suggestion
Bugfix
```

2020-12-02 08:54 UTC, gilles-peskine-arm commented on ChangeLog.d/missing-debug-message-arguments_mbedtls_ssl_decrypt_buf.txt
> +  * Add missing arguments of debug message in mbedtls_ssl_decrypt_buf
And while you're at it, please add a full stop at the end of the sentence.
```suggestion
  * Add missing arguments of debug message in mbedtls_ssl_decrypt_buf.
```

2020-12-02 16:47 UTC, gilles-peskine-arm approved these changes

2020-12-02 16:50 UTC, paul-elliott-arm approved these changes
Thanks for the changes

2020-12-03 11:29 UTC, merged