Update the values of PSA Crypto API macros to version 1.0.0
ARMmbed/mbedtls pull request #3948
Opened 2020-12-07 20:10 UTC by bensze01

## Description
This PR contains what I believe to be  the minimum changes required for us to be compatible with the stable storage format going forward.

## Status
**READY**

## Requires Backporting
No, PSA only

## Migrations
The storage format changes to be in line with the PSA Crypto API version 1.0.0

## Todos
- [ ] Storage format tests updated

2020-12-07 20:44 UTC, gilles-peskine-arm requested changes
I made a first pass and verified that this is a sensible change which affects the areas of the code that it should affect, no more no less, except:

• Missing changes of key storage tests in `test_suite_psa_crypto_persistent_key.data`.
• Missing changelog entry.

Other than some minor issues in `crypto_compat.h`, and provided that the new values are the ones we want (which I will validate after posting this review), this looks good to me.

2020-12-07 20:44 UTC, gilles-peskine-arm commented on include/psa/crypto_compat.h
> + * Deprecated PSA Crypto stream cipher algorithms (PSA Crypto API  <= 1.0 beta3)
Deprecated values should go inside the `MBEDTLS_DEPRECATED_REMOVED` block just above.

2020-12-07 20:44 UTC, gilles-peskine-arm commented on include/psa/crypto_compat.h
> +    PSA_ALG_STREAM_CIPHER
```suggestion
    MBEDTLS_DEPRECATED_CONSTANT( PSA_ALG_STREAM_CIPHER )
```
and likewise for CHACHA20

2020-12-07 20:44 UTC, gilles-peskine-arm commented on include/psa/crypto_values.h
> + *   and algorithm id #PSA_ALG_STREAM_CIPHER.
Minor: repeating the algorithm identifier isn't useful.

2020-12-07 21:39 UTC, gilles-peskine-arm commented
I merged a29455144616e34dd51973061d186317b0cfa5a4 from this pull request with 4b11b251604111a6b12241497c8b958103e4025f from https://github.com/ARMmbed/mbedtls/pull/3936 and ran `programs/test/verify_psa_macros`. It passes.

There are warnings, but none of them are problematic. Excluding size macros and get/test macros,
```
programs/test/verify_psa_macros 2>&1 | grep -Ev '_(LENGTH|SIZE)[( ]|_(GET|IS)_'
```
only lists identifers that Mbes TLS doesn't declare because they're unsupported, plus:
```
WARN:  PSA_ALG_AEAD_WITH_DEFAULT_LENGTH_TAG(aead_alg) is not defined
WARN:  PSA_ALG_AEAD_WITH_SHORTENED_TAG(aead_alg, tag_length) is not defined
WARN:  PSA_ALG_NONE is not defined
WARN:  PSA_KEY_ID_NULL is not defined
WARN:  PSA_KEY_LOCATION_PRIMARY_SECURE_ELEMENT is not defined
```
The `AEAD_WITH_xxx_TAG` macros have an older name. I verified manually that their new definitions are correct, as well as the corresponding macros for MAC which the current version of `verify_psa_macros` does not verify adequately.

2020-12-07 23:33 UTC, bensze01 commented
@gilles-peskine-arm I think I've addressed all of the feedback.

2020-12-08 08:51 UTC, gilles-peskine-arm approved these changes

2020-12-08 09:17 UTC, mpg approved these changes
After reviewing the changes and using the test scripts, I'm happy with this PR.

I left an optional suggestion for improving internal documentation, but it could be left for later.

2020-12-08 09:39 UTC, gilles-peskine-arm commented on tests/scripts/test_psa_constant_names.py
> +        self.hash_algorithms = set(['0x020000fe'])
That's more my failing originally. They have to have correct values for `PSA_ALG_IS_xxx`, and to be distinct from any current or likely values of a valid `PSA_ALG_xxx`. So for example hash algorithms have the pattern `0x020000nn`, and the spec starts from low values of `nn`, so the numerical value for testing takes `n==0xfe` (why not `n==0xff` as before? It doesn't matter).

2020-12-08 09:45 UTC, bensze01 commented on tests/scripts/test_psa_constant_names.py
> +        self.hash_algorithms = set(['0x020000fe'])
`hash_algorithms` ended with `0xfe` before my patch as well, so I left it like that.

2020-12-08 09:48 UTC, bensze01 commented on tests/scripts/test_psa_constant_names.py
> +        self.hash_algorithms = set(['0x020000fe'])
Oh, It's because of `PSA_ALG_ANY_HASH `- which incidentally wasn't updated. Give me a moment.

2020-12-08 09:50 UTC, gilles-peskine-arm commented on tests/scripts/test_psa_constant_names.py
> +        self.hash_algorithms = set(['0x020000fe'])
Ah, good spot. I should have put a comment about this.

2020-12-08 09:51 UTC, bensze01 commented on tests/scripts/test_psa_constant_names.py
> +        self.hash_algorithms = set(['0x020000fe'])
Sorry, false alarm. `PSA_ALG_ANY_HASH `*was* updated. I was just looking at the wrong branch.

2020-12-08 10:03 UTC, merged