Make PSA config options definitive
ARMmbed/mbedtls pull request #3980
Opened 2020-12-31 19:42 UTC by d3zd3z

When MBEDTLS_PSA_CRYPTO_CONFIG is enabled, we define appropriate
configurations with the legacy names.  Unfortunately, for the most part,
these are already defined by the existing configuration file.

To make this more definitive, add undefs for all of the legacy config
defines that are controlled by the PSA config.

Signed-off-by: David Brown <david.brown@linaro.org

## Status
**READY**

## Requires Backporting
NO  

## Migrations
Change ifdefs under `MBEDTLS_PSA_CRYPTO_CONFIG` to be effective. Could cause change if something was being defined that wasn't selected by a PSA config.

NO

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

2021-01-04 15:09 UTC, gilles-peskine-arm requested changes
Undefining `MBEDTLS_xxx_C` and friends is wrong. If `config.h` defines these symbols, that's perfectly legitimate.

I don't see any harm in undefining `MBEDTLS_PSA_BUILTIN_xxx`, but I don't see the point either.

2021-01-04 15:09 UTC, gilles-peskine-arm commented on include/mbedtls/config_psa.h
> +#undef MBEDTLS_ECDSA_DETERMINISTIC
Undefining `MBEDTLS_xxx` here is definitely wrong. Consider an application that uses both `mbedtls_pk_sign` and 
`psa_sign_hash` (perhaps via two different libraries). Its `config.h` will need to enable both `MBEDTLS_ECDSA_C` and `PSA_WANT_ALG_ECDSA`. This is true regardless of the configuration mode.

2021-01-04 15:56 UTC, d3zd3z commented
> Undefining MBEDTLS_xxx_C and friends is wrong. If config.h defines these symbols, that's perfectly legitimate.

Maybe the solution here is that we need to be undefining all of these in config.h for testing, then?

2021-01-04 16:02 UTC, gilles-peskine-arm commented
> Maybe the solution here is that we need to be undefining all of these in config.h for testing, then? Right now, the PSA config tests don't actually test much, because everything is already defined in config.h.

Yes! But there's another, bigger thing we need to do anyway to have effective testing of PSA config, which is to change `MBEDTLS_xxx` dependencies in PSA test code to `PSA_WANT_xxx`.

2021-01-04 16:18 UTC, gilles-peskine-arm commented
See also https://github.com/ARMmbed/mbedtls/issues/3679 regarding the medium-term goal for how the testing is done in `all.sh`.

2021-01-05 23:05 UTC, gilles-peskine-arm requested changes

2021-01-05 23:05 UTC, gilles-peskine-arm commented on tests/scripts/getdefines.py
> +"""Extract defines create by header
I'm not convinced by this approach. It seems a little roundabout and fragile. If `config_psa.h` is missing a `#define` that it should have, the tests won't catch it.

`scripts/config.py` already knows which symbols in `config.h` are crypto. How about adding a command that turns off all crypto symbols?

2021-04-27 13:32 UTC, daverodgman commented
@ronald-cron-arm is covering this in #3680

2021-04-27 13:32 UTC, closed without merging