Support HMAC_DRBG in SSL test programs
ARMmbed/mbedtls pull request #4020
Opened 2021-01-13 19:37 UTC by gilles-peskine-arm

* Unify the RNG-related code of `ssl_client2` and `ssl_server2` into `ssl_test_lib`. This is a continuation of #3986.
* Add support for HMAC_DRBG in `ssl_test_lib`. Exercise the HMAC_DRBG support in `all.sh`.
* Do run SSL tests when HMAC_DRBG is disabled: this exercises non-deterministic ECDSA. This part does not depend on the rest and should be backported.

A follow-up will add support for the PSA external RNG in SSL test programs, fulfilling #3883.

2021-01-22 14:48 UTC, ronald-cron-arm requested changes
This looks almost good to me, just minor comments.

2021-01-25 12:48 UTC, gilles-peskine-arm commented on tests/Makefile
> +TEST_OBJS_DEPS = $(wildcard include/test/*.h include/test/*/*.h)
No. I forgot to add a comment explaining why, thanks for prodding me.

2021-01-25 12:51 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
> +    # HMAC_DRBG is disabled in this configuration, randomized ECDSA is used
ECDSA can be either deterministic or randomized. Internally, it needs to generate a secret value _k_ such that the same value of _k_ is never used to sign different messages with the same private key. Deterministic ECDSA generates _k_ using HMAC_DRBG seeded from the private key and the message. Randomized ECDSA generates _k_ randomly (as in, the probability of repeating _k_, whether it's with the same message or with distinct messages, is negligible). The random generator might involve a DRBG inside, but that's inside the RNG black box, which could be using a different DRBG algorithm and could be running on a different processor if there's an external RNG driver.

2021-01-25 15:08 UTC, ronald-cron-arm commented on tests/scripts/all.sh
> +    # HMAC_DRBG is disabled in this configuration, randomized ECDSA is used
ok thanks for the clarification.

2021-01-25 15:19 UTC, ronald-cron-arm approved these changes
Thanks for the changes and clarifications.

2021-01-28 18:52 UTC, bensze01 approved these changes
Everything looks good to me.

2021-01-29 07:58 UTC, merged