Add PSA Crypto driver delegation fro AEAD functions
ARMmbed/mbedtls pull request #4050
Opened 2021-01-18 15:22 UTC by stevew817

## Description
Add driver delegation as per the already established paradigms and the design document in `docs/proposed/psa-driver-interface.md`.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [X] Tests
- [X] Documentation
- [X] Changelog updated

## Steps to test or reproduce
Testing is covered by existing test suites, which verify that the existing implementation still works (the test driver is a stub). For actually testing the driver itself, a generic approach would need to be chosen first.

It is assumed that whoever implements drivers would also need to do their own testing for their specific driver constellation.

2021-01-18 16:47 UTC, stevew817 commented
If somebody could look at the test failure, that'd be great. I assume it's a flake from the CI system.

2021-01-18 17:27 UTC, ronald-cron-arm commented
Yes that's just a "git fetch" to GitHub that failed.

2021-01-29 13:11 UTC, ronald-cron-arm requested changes
As for #4043, the driver delegation in this PR is not aligned with the organization of the PSA implementation with respect to the PSA driver interface that we are currently trying to move to. The code organization is described in the psa-crypto-implementation-structure.md document in PR #3933 and an example for unauthenticated operations can be found here (for ciphers).

2021-03-19 11:41 UTC, stevew817 commented
Superseded by #4240

2021-03-19 11:41 UTC, closed without merging