Actually use the READ_TIMEOUT_MS in the example DTLS client and server
ARMmbed/mbedtls pull request #4075
Opened 2021-01-27 17:22 UTC by rrlapointe

## Description
`programs/ssl/dtls_client.c` and `programs/ssl/dtls_server.c` each contain a `#define READ_TIMEOUT_MS` that was previously used to specify the read timeout. Since 97fd52c529e293f98674f313fb2da9a9f8b85fbc, those defines have been useless / not serving their intended purpose. This PR makes those defines serve their purpose again.

## Status
**READY**

## Requires Backporting
I don't know

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

2021-03-01 14:56 UTC, mstarzyk-mobica requested changes

2021-03-01 14:56 UTC, mstarzyk-mobica commented on programs/ssl/dtls_server.c
> +#define READ_TIMEOUT_MS 10000   /* 10 seconds */
Please put this in separate commit.

2021-03-01 15:00 UTC, rrlapointe commented on programs/ssl/dtls_server.c
> +#define READ_TIMEOUT_MS 10000   /* 10 seconds */
ok

2021-03-03 12:05 UTC, mstarzyk-mobica approved these changes

2021-03-15 19:51 UTC, gilles-peskine-arm requested changes
Thank you for giving the sample programs a little love! To finish this, can you please:

1. Add a changelog entry (see `ChangeLog.d/00README.md`). Suggested text: “Fix the setting of the timeout in DTLS sample programs.”.
2. Make a similar pull request to the long-time support `mbedtls-2.16` branch which has the same issue.

2021-03-15 21:10 UTC, rrlapointe commented
@gilles-peskine-arm I added the changelog entry in `ChangeLog.d/dtls_sample_use_read_timeout.txt` and I opened the backport pull request ( #4230 ).

2021-03-16 08:47 UTC, gilles-peskine-arm approved these changes

2021-03-17 13:29 UTC, mstarzyk-mobica approved these changes

2021-03-17 13:39 UTC, merged