wrong RSA_PRV_DER_MAX_BYTES for odd MBEDTLS_MPI_MAX_SIZE
ARMmbed/mbedtls pull request #4094
Opened 2021-02-01 14:20 UTC by d-otte

This is the PR for issue #4093

# Description

It adds parenthesis to fix the computation of `RSA_PRV_DER_MAX_BYTES` and also adds parenthesis to other macros to make them safer to use.

2021-02-01 15:57 UTC, yanesca submitted a review, later dismissed
Looks good to me.

2021-02-01 16:41 UTC, chris-jones-arm requested changes
Hi @d-otte, thanks for the well written bug report and subsequent PR. I'm generally happy with this PR apart from a few minor house-keeping points shown below.

Also as you mentioned in your issue, this bug exists in the 2.16 branch as well as the 2.7 branch. Could you please provide backports for both of these branches along with the changelog entry (mentioned below).

2021-02-01 16:41 UTC, chris-jones-arm commented on library/pkwrite.c
>  {
Minor: try to avoid commit messages over 80 characters as it makes github render them strangely.

2021-02-01 16:41 UTC, chris-jones-arm commented on library/pkwrite.c
>  {
As this is a bug fix (and potential security risk) can you please add a changelog entry. Details can be found under `ChangeLog.d/00README.md` and if you have any other issues don't hesitate to ask.

2021-02-02 11:25 UTC, chris-jones-arm commented
Thanks for adding the changelog @d-otte! Unfortunately it now seems to be failing CI (trailing whitespace and missing newline in the changelog). Could you please fix these errors and also rename the changelog entry to "Security" as opposed to "Bugfix" as I think this constitutes a security risk due to the potential buffer overflow. Sorry if my earlier wording was not clear on this.

2021-02-02 15:35 UTC, chris-jones-arm approved these changes
I'm happy with this now, thanks for making the changes.

2021-02-02 16:15 UTC, merged