Add missing const attribute to Public Key API
ARMmbed/mbedtls pull request #4102
Opened 2021-02-02 14:23 UTC by mstarzyk-mobica

Signed-off-by: Mateusz Starzyk <mateusz.starzyk@mobica.com>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-02-05 09:26 UTC, mpg requested changes
Looks good to me except for two style issues.

2021-02-05 09:26 UTC, mpg commented on include/mbedtls/pk.h
> +int mbedtls_pk_write_key_der(const mbedtls_pk_context *ctx, unsigned char *buf, size_t size );
Style: missing space before `const` (sorry).

2021-02-05 09:26 UTC, mpg commented on library/pkwrite.c
> +int mbedtls_pk_write_key_der(const mbedtls_pk_context *key, unsigned char *buf, size_t size )
Style: same.

2021-02-05 11:08 UTC, mpg approved these changes
Thanks for fixing the style issues. Looks all good to me now.

2021-02-09 17:08 UTC, chris-jones-arm approved these changes
Looks good to me.

2021-02-09 17:12 UTC, chris-jones-arm commented
Before we merge, are we waiting for the other const PR's and the changelog PR or are we merging as we go?

2021-02-10 09:07 UTC, mpg commented
No I think we can merge const PRs as we go, and then merge the ChangeLog PR last.

2021-02-10 09:08 UTC, merged