Remove certs module from mbedtls.
ARMmbed/mbedtls pull request #4119
Opened 2021-02-08 15:38 UTC by mstarzyk-mobica

Resolves #4080

2021-02-12 13:40 UTC, ronald-cron-arm commented
Thus the error when running build_default_make_gcc_and_cxx (head job) is:
******************************************************************

* build_default_make_gcc_and_cxx: test: verify header list in cpp_dummy_build.cpp 

* Thu Feb 11 17:50:57 UTC 2021

******************************************************************

21d20

< config_psa.h


******************************************************************

* build_default_make_gcc_and_cxx: build: Unix make, incremental g++ 

* Thu Feb 11 17:50:57 UTC 2021

******************************************************************

  CXX   test/cpp_dummy_build.cpp

test/cpp_dummy_build.cpp:102:24: fatal error: test/certs.h: No such file or directory

compilation terminated.

Makefile:318: recipe for target 'test/cpp_dummy_build' failed

Makefile:14: recipe for target 'programs' failed

make[1]: *** [test/cpp_dummy_build] Error 1

make: *** [programs] Error 2

^^^^build_default_make_gcc_and_cxx: build: Unix make, incremental g++: command make TEST_CPP=1 -> 2^^^^


******************************************************************

* Done, cleaning up 

* Thu Feb 11 17:50:57 UTC 2021

******************************************************************


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FAILED: 1

build_default_make_gcc_and_cxx: build: Unix make, incremental g++: command make TEST_CPP=1 -> 2

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-02-12 13:43 UTC, ronald-cron-arm commented
The other errors in the merge job are just CI problems (repo cloning failure) and the I guess expected failure of the ABI-API checking job.

2021-03-01 18:23 UTC, chris-jones-arm requested changes
A few small things to change but otherwise I think this is looking good to me. I would like a more experienced team member to go over though to ensure the design is correct.

2021-03-04 10:12 UTC, mpg commented on include/mbedtls/compat-1.3.h
>  #if defined MBEDTLS_CCM_C
Note: it is indeed being removed by #4150 so I'd suggest not changing it here in order to avoid conflicts.

2021-03-04 10:22 UTC, mpg reviewed
This is looking good to me, except for a typo and the few minor things already pointed out by Chris.

2021-03-04 10:22 UTC, mpg commented on ChangeLog.d/remove_certs.txt
> +     This contributes to minimizing libarry API and discourages users
Typo: libarry -> library.

2021-03-18 17:37 UTC, chris-jones-arm requested changes
A few small removals that I missed on my first pass, otherwise this has addressed all previous comments.

Also, I think it's already been talked about but please add more commits instead of rebasing. It can make it a lot harder and longer to understand the new changes that have been made from before.

2021-03-18 17:37 UTC, chris-jones-arm commented on scripts/data_files/query_config.fmt
> +#include "test/certs.h"
Note: reminder to remove this from the `query_config.fmt` as well as the previous, `query_config.c`.

2021-03-19 15:33 UTC, chris-jones-arm approved these changes
Thanks for the changes, I'm happy with this now.

2021-03-29 09:13 UTC, mpg approved these changes
Looks all good to me.

2021-03-29 09:14 UTC, mpg commented
The pr-head job is fully passing, and the pr-merge job is only failing in the ABI-API check, which is fully expected considering this is targeting 3.0.

2021-03-29 09:16 UTC, merged