Fix memory leak in error case in psa_crypto
ARMmbed/mbedtls pull request #4131
Opened 2021-02-09 19:06 UTC by paul-elliott-arm

## Description

In psa_generate_derived_key_internal() an error case was returning directly rather than jumping to the exit label, which meant that an allocated buffer would not be free'd.

Found via coverity.

## Status
**READY**

## Requires Backporting
NO  

(New code, bug does not exist in LTS branches)

## Migrations

NO

2021-02-09 19:10 UTC, gilles-peskine-arm approved these changes

2021-02-09 19:11 UTC, gilles-peskine-arm requested changes

2021-02-09 19:11 UTC, gilles-peskine-arm commented on ChangeLog.d/fix_psa_crypto_leak.txt
> +   * Fix memory leak that occured in error case in psa_generate_derived_key_internal()
Please use proper English in changelog entries.
```suggestion
   * Fix a memory leak in an error case in psa_generate_derived_key_internal().
```

2021-02-12 14:56 UTC, ronald-cron-arm approved these changes

2021-02-15 10:37 UTC, gilles-peskine-arm approved these changes

2021-02-15 10:38 UTC, merged