ssl-opt.sh: add --priority=normal to gnutls-serv
ARMmbed/mbedtls pull request #4136
Opened 2021-02-10 12:56 UTC by daverodgman

For calls to gnutls-serv where --priority is not specified, explicitly
add the default value: --priority=normal. This is needed for some tests
on Ubuntu 20.04 (gnutls-serv 3.6.13).

Signed-off-by: Dave Rodgman <dave.rodgman@arm.com>

## Steps to test or reproduce
./ssl-opt.sh -f "DTLS fragmenting: gnutls server, DTLS 1.0"

2021-02-10 13:23 UTC, gilles-peskine-arm requested changes

2021-02-10 13:23 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +        GNUTLS_SERV=1
`GNUTLS_SERV` is also the path passed as an optional input in the initial environment. I\m not sure if using this name at this point breaks anything, but at best it's fragile.

2021-02-10 13:23 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +detect_gnutls_serv() {
Please use a name and interface similar to `is_polar`.

2021-02-10 13:23 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +    if echo "$1" | grep 'gnutls-serv \|gnutls-serv$' >/dev/null; then
Please favor `case` and other shell built-in features over external calls such as `grep`. It's noticeably faster when running a small number of test cases.

2021-02-10 13:23 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +G_PRI="--priority=NORMAL"
(commit message) Can you give a specific example of a test case that requires it?

2021-02-10 13:30 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +        GNUTLS_SERV=1
It does break something: it interferes with `requires_gnutls`.

2021-02-11 14:36 UTC, tom-daubney-arm approved these changes
LGTM, thanks.

2021-02-15 09:54 UTC, gilles-peskine-arm requested changes

2021-02-15 09:54 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +        fi
Please use `case` in preference to `grep`: it has fewer quoting gotchas and it's faster.
```suggestion
        case "$SRV_CMD" in
              *--priority*) :;;
              *) SRV_CMD="$SRV_CMD $G_PRI";;
        esac
```
and likewise below

2021-02-15 09:54 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +    *gnutls-cli\ *)
Something like `gnutls-cli-3.4.5` is plausible but wouldn't be caught here.

2021-02-15 09:54 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> +G_PRI="--priority=NORMAL"
Ok, this is used in two places, but I'm not sure it warrants a variable. If it does, it should be in a more local scope and with a more explicit name. It's hard to understand what this is for here, whereas it's easy to understand what `--priority=NORMAL` does in context.

2021-02-15 12:53 UTC, daverodgman commented
I've updated in line with Gilles' comments. It now passes all the gnutls tests on 20.04 (these pass with or without the PR on 16.04).

2021-02-15 14:26 UTC, gilles-peskine-arm approved these changes

2021-02-16 11:03 UTC, tom-daubney-arm approved these changes
Makes sense. LGTM.

2021-02-16 14:37 UTC, merged