Improve the visibility of some informations
ARMmbed/mbedtls pull request #4175
Opened 2021-02-25 12:10 UTC by mpg

## Description

Currently it's a bit hard for a user or contributor coming to the project on github to discover some basic information such as:

- how to report security bugs (is on the tf.org wiki, which itself was not linked anywhere from the source tree)
- what branches are currently maintained

This PR tries to improve the situation by adding a few files with explicit names (some recognized by github) and cross-referencing with existing documents.

Some of this information is version-independent and arguably should be maintained out-of-tree. However I'm adding them here without waiting for our version-independent docs repo to be ready, in the spirit of incremental improvement: I believe this PR is a strict improvement over the status quo and that it does not make future improvements harder. (When the docs repo is ready we can move the content of most files there and have the in-tree file just point at the appropriate place in the docs repo.)

## Status
**READY**

## Requires Backporting

Debatable. In terms for visibility, I think the default branch is the most important, so we might choose to skip backports until the version-independent docs repo is ready, and add pointers to it from the LTS branches only at this point.

2021-02-25 12:18 UTC, yanesca commented on .github/issue_template.md
> +**Note:** to report a security vulnerability, see
Maybe we could explain that by security vulnerability we mean any bug that might have a security impact (eg. memory corruption errors), they don't have to have an PoC exploit taking over the machine ready to go.

2021-02-25 12:21 UTC, yanesca approved these changes
Have a minor suggestion for improvement, other than that it looks good to me.

2021-02-25 12:51 UTC, paul-elliott-arm reviewed
I feel like either the Contributing section in Readme.md should point to the security page as well (in case of vulnerabilities / suspected security vulnerabilities), or the contributing page should mention it.

I think changing the issue template is good, but some people clearly don't read the template, so I would kinda prefer this to be a last line of defense.

2021-02-25 13:45 UTC, gilles-peskine-arm requested changes
Thanks for taking the time to improve these files!

I'm not convinced that adding more small files to the tree is the right way. It puts more information available at the user's fingertips, but it also creates more silos and can lead users to give up finding the file containing what they're after. I think we should have less version-independent information in-tree, and instead host it on https://github.com/ARMmbed/mbedtls-docs. https://github.com/ARMmbed/mbedtls-docs isn't fully set up yet — we intend to have a place where the documentation is rendered and is complemented by the API reference — but it's ready at least for self-contained Markdown and PDF documents.

2021-02-25 13:45 UTC, gilles-peskine-arm commented on BRANCHES.md
> +- one or more LTS branches: these only get bug fixes and security fixes.
```suggestion
- one or more long-time support (LTS) branches: these only get bug fixes and security fixes.
```

2021-02-25 13:45 UTC, gilles-peskine-arm commented on BRANCHES.md
> +- the development branch: this is where new features lands, as well as bug
There's also `master`, which gets the releases from `development`.

2021-02-25 13:45 UTC, gilles-peskine-arm commented on BRANCHES.md
> +API compatibility in the development branch between major version changes. We
We don't actually maintain API compatibility in `development`. We do in `master`. It happens from time to time that we tweak a new feature that just landed into `development` if it hasn't been part of a release yet.

2021-02-25 13:45 UTC, gilles-peskine-arm commented on BRANCHES.md
> +compatibility (same definition as API except with re-linking instead of
“same definition as API” but you didn't actually define “API compatibility”. Please add that expression to the previous paragraph where you define the concept.

2021-02-25 13:45 UTC, gilles-peskine-arm commented on BRANCHES.md
> +- [development](https://github.com/ARMmbed/mbedtls/)
As above: `master`. Most users should pull from `master`.

2021-02-25 13:45 UTC, gilles-peskine-arm commented on SECURITY.md
> +## Reporting Vulneratibilities
It's good to have these instructions, but many users won't be looking for `SECURITY.md` when reporting a bug. How about having `BUGS.md` instead or in addition?

2021-02-25 13:45 UTC, gilles-peskine-arm commented on .github/issue_template.md
> +_Note:_ this is a template, please remove the parts that are not
A lot of issue submitters keep the template and type their own stuff above or below. I don't think italicizing “Note” will improve that. Can we make this leading sentence punchier?

2021-03-16 10:43 UTC, gilles-peskine-arm commented on BRANCHES.md
> +- [mbedtls-2.7](https://github.com/ARMmbed/mbedtls/tree/mbedtls-2.7) - end of life in March 2021!
Now retired.

2021-03-16 11:09 UTC, gilles-peskine-arm commented
With Manuel's agreement, I've pushed updates that address my change requests.

I have not made any changes to the issue template because this PR improves it and I don't think any of the comments on that part are blockers, so let's merge that and handle the issue template in a follow-up. For the issue template, I propose to do some radical restructuring: instead of having a single document where users are supposed to remove sections (but they never do), let's [have multiple templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) which GitHub now supports.

2021-03-16 11:27 UTC, yanesca submitted a review, later dismissed
Looks good to me.

2021-03-16 22:14 UTC, gilles-peskine-arm commented
I have looked at how we can use of [the GitHub template chooser](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository). You can see the code in https://github.com/gilles-peskine-arm/mbedtls/tree/issue-templates (to become a pull request once this one is merged) and I've made that the default branch in my fork so you can play with it at https://github.com/gilles-peskine-arm/mbedtls/issues/new/choose (which is what the “New issue” button points to).

2021-03-24 11:16 UTC, paul-elliott-arm submitted a review, later dismissed

2021-03-24 11:16 UTC, paul-elliott-arm commented on BRANCHES.md
> +API compatibility in the `master` branch between major version changes. We
I would make the usual D&I comment here that I thought we were moving away from using 'master', but I guess this can change when we make that change

2021-03-29 09:54 UTC, gilles-peskine-arm commented
@mpg Did you mean to undo the changes I made in a force-push? If so why?

2021-03-29 10:36 UTC, mpg commented
@gilles-peskine-arm Sorry, that was a bad mistake from me. Do you still have a copy of the changes?

2021-03-29 10:40 UTC, mpg commented
Ok, github had a copy, I've restored your changes now. Sorry again. Thanks for noticing.

2021-03-31 09:20 UTC, paul-elliott-arm approved these changes
LGTM

2021-03-31 09:43 UTC, mpg reviewed
I reviewed @gilles-peskine-arm commits and I approve them. (github doesn't let me check "approve" cause I'm the PR author)

2021-03-31 09:45 UTC, mpg commented
> Requires Backporting? Debatable. In terms for visibility, I think the default branch is the most important, so we might choose to skip backports until the version-independent docs repo is ready, and add pointers to it from the LTS branches only at this point.

What do you all think? I'm inclined not to backport for now. Most of the files added here belong in the version-independent repo in the long run, and the changes to the github templates only matter for the default branch.

2021-03-31 09:46 UTC, gilles-peskine-arm approved these changes
I'm re-recording my approval of Manuel's part, and relaying [Manuel's approval of my part](https://github.com/ARMmbed/mbedtls/pull/4175#pullrequestreview-625094726).

~I'll push a 2.16 backport.~ @mpg I just saw your message, I agree, let's no bother with a backport.

2021-03-31 09:48 UTC, merged