Backport 2.7: Fix stack corruption in mbedtls_net_poll with large file descriptor
ARMmbed/mbedtls pull request #4181
Opened 2021-03-01 15:47 UTC by gilles-peskine-arm

Partial backport of the bug fix in #4173: 2.7 doesn't have `mbedtls_net_poll`, but it has `mbedtls_net_recv_timeout` which has the same bug. As with 2.16, I didn't backport the new tests because they're in a new test suite and there's a mild but nonzero concern about the test code's portability.

2021-03-03 09:44 UTC, mpg approved these changes
LGTM

2021-03-03 09:45 UTC, yanesca commented
I just noticed that the CI is failing. @gilles-peskine-arm could you please have a look at the failures?

2021-03-03 09:48 UTC, mpg requested changes

2021-03-03 09:48 UTC, mpg commented on library/net_sockets.c
> +        return( MBEDTLS_ERR_NET_POLL_FAILED );
The CI points out there's no such error code in the 2.7 branch, I think you mean `MBEDTLS_ERR_NET_RECV_FAILED`. But now that my attention has been drawn to it, it's probably incorrect in the other branches as well.

2021-03-03 11:24 UTC, gilles-peskine-arm commented on library/net_sockets.c
> +        return( MBEDTLS_ERR_NET_POLL_FAILED );
I amended the commit to return `MBEDTLS_ERR_NET_RECV_FAILED`. I rewrote the history to avoid having a non-building commit.

2021-03-03 12:00 UTC, mpg approved these changes
LGTM

2021-03-03 12:15 UTC, yanesca approved these changes
LGTM.

2021-03-04 10:02 UTC, mpg commented
The failure in pr-head looks spurious (as all tests passed in pr-merge), but OTOH it does not look like one of the usual issues, so just to be on the safe side I've restarted the job.

2021-03-04 12:15 UTC, merged