Improve bignum exp-mod simple power analysis leak detailed in #4231
ARMmbed/mbedtls pull request #4234
Opened 2021-03-16 13:25 UTC by colinoflynn

## Description
Fix simple SPA attack in exp-mod as described in issue #4231.

## Status
**READY**

## Requires Backporting
YES

Probably should be pushed to other branches due to simplicity.

## Todos
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
See #4231 for reproduction steps.

2021-03-23 21:03 UTC, bensze01 submitted a review, later dismissed
Looks good to me.

2021-03-23 21:20 UTC, bensze01 commented
Do add a Changelog, please.

2021-03-23 21:42 UTC, colinoflynn commented
> Do add a Changelog, please.

Sorry new to mbedtls - is this for me todo, not sure how to add PR on ChangeLog (looks like ChangeLog updated on each release so didn't see the staging area to PR on).

Based on https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog#L52 I assume it would look like this as part of 'Security' seems most fitting:

   * Fix simple power analysis (SPA) leak in mbedtls_mpi_exp_mod that leaked each
      bit despite windowed implementation of exp_mod. See #4231 for more information
      including proof of concept, fixed in #4234.

2021-03-23 22:41 UTC, gilles-peskine-arm commented
Please create a file in `ChangeLog.d`, see `ChangeLog.d/00README.md` and examples. Adjusting your proposed text to our style habits:

> Mitigate a simple power analysis (SPA) leak in mbedtls_mpi_exp_mod that leaked each
bit despite a windowed implementation of exp_mod. See #4231 for more information.

2021-03-23 22:54 UTC, gilles-peskine-arm requested changes
I'm not familiar enough with power analysis to judge how effective this change is, but it's semantically correct and at least a step in the right direction.

All it's missing is some documentation: comment, changelog entry.

2021-03-23 22:54 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
In your experience, do compilers respect the order of the tests? Semantically, they don't have to, since it's correct to access the value of `state` independently of the value of `ei` and vice versa.

2021-03-23 22:54 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
It is not at all obvious to the average maintainer of Mbed TLS that the order of these tests matters. Please add a comment with a brief explanation and a reference to https://github.com/ARMmbed/mbedtls/issues/4231.

2021-03-23 22:54 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
Would reducing the use of boolean tests reduce the leakage? E.g. `if( ( ei | state ) == 0 )`

2021-03-23 23:41 UTC, colinoflynn commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I assume this will still result in the same assembly output - checking each variable in sequence. The issue with the original code is that the `ei` (which is the secret bit) gets checked first. Any conditional check has inherent side channel power leakage - you can see an example of this in a password check at https://github.com/newaetech/chipwhisperer-jupyter/blob/master/courses/sca101/Lab%202_1B%20-%20Power%20Analysis%20for%20Password%20Bypass%20(MAIN).ipynb .

2021-03-23 23:48 UTC, colinoflynn commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I'm not a real hard-core compiler person tbh - my understanding is they always respect the order as they guarantee "short circuit" condition for `&&`, which is why you can do if `(ptr && *ptr == VALUE)` to check for a non-NULL pointer and check the dereference in one conditional. This is referenced by https://en.wikipedia.org/wiki/Short-circuit_evaluation (although I avoid usage like that in practice). Do you think I should reorder the patch to do this like:

```
if( state == 0 )
{
    if ( ei == 0) 
    {
        continue;
    }
}
```
I was trying to avoid changing the style very much to be honest. But A comment as you suggest might be enough such that it's more clear in the future about the order - I'll add a note that the `ei` comparison has a leakage in it.

2021-03-23 23:59 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I wouldn't expect nested ifs vs `&&` to make a difference: I'd expect they tend to reach the same intermediate representation inside a compiler.

Short circuit evaluation is guaranteed when it's semantically observable, but as far as the C language definition is concerned, accessing a non-volatile variable is not observable, and `state == 0 && ei == 0` and `ei == 0 && state == 0` have the same semantics. A compiler could decide that one of the variables is more likely to be 0 than the other and test this one first, but I have no idea how likely this is. Unfortunately, C compilers don't care about side channels.

2021-03-24 00:02 UTC, colinoflynn commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
Thanks for the details of how it works there - maybe then a comment is enough for now? I know the idea of side channel protection at compiler levels is a lot of ongoing work - the PR is mostly a "slight improvement" anyway. From what I've seen the compilers mostly evaluate in this order, but as I mention my "experience" is limited to a handful of compilers and I haven't done anything like a real evaluation.

2021-03-24 00:34 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I want a comment here so that a reader would know that the order is important and why. Unless we have some data on compiler optimizations, there's no need to discuss the risk of compiler optimization messing up the order in the comment.

2021-04-29 21:58 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I tested the effect of this patch with two build settings that are popular Mbed TLS for Mbed TLS: Clang optimized for speed on x86 and GCC optimized for size on Cortex-M.

With `gcc -mthumb -mcpu=cortex-m0plus` (gcc 7.3.1), here's the assembly code for the two comparisons that this PR changes, before the change:
```
        .loc 1 2246 0
        movs    r1, r2
        orrs    r1, r3
        beq     .L614
        .loc 1 2249 0
        cmp     r3, #0
        bne     .L615
        .loc 1 2249 0 is_stmt 0 discriminator 1
        cmp     r2, #1
        bne     .L615
        .loc 1 2254 0 is_stmt 1
        add     r3, sp, #68
.LVL1129:
        str     r3, [sp]
.LVL1130:
        ldr     r1, [sp, #20]
        ldr     r3, [sp, #16]
        movs    r2, r7
.LVL1131:
        ldr     r0, [sp, #32]
        bl      mpi_montmul.isra.1
```

And after:
```
        movs    r1, r2
        orrs    r1, r3
        beq     .L614
        .loc 1 2249 0
        cmp     r2, #1
        bne     .L615
        .loc 1 2249 0 is_stmt 0 discriminator 1
        cmp     r3, #0
        bne     .L615
        .loc 1 2254 0 is_stmt 1
        add     r3, sp, #68
.LVL1129:
        str     r3, [sp]
.LVL1130:
        ldr     r1, [sp, #20]
        ldr     r3, [sp, #16]
        movs    r2, r7
.LVL1131:
        ldr     r0, [sp, #32]
        bl      mpi_montmul.isra.1
```

The compiler optimized `state == 0 && ei == 0` to `(ei | state) != 0`, and changing the order of arguments doesn't affect that. The secret variable `ei` is read no matter what the state is. For `state == 1 && ei == 0`, it does check `state` first.

And with Clang 10 `-O3` on x86_64, I get exactly the same code before and after your patch. With some debugging info omitted:
```
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:state <- $rax
        .loc    9 2246 24 is_stmt 1     # source/library/bignum.c:2246:24
        movq    %rdx, %rcx
        orq     %rax, %rcx
.Ltmp2535:
        .loc    9 0 0 is_stmt 0         # source/library/bignum.c:0:0
        movl    $0, %ecx
.Ltmp2536:
        .loc    9 2246 24               # source/library/bignum.c:2246:24
        je      .LBB40_132
.Ltmp2537:
# %bb.136:                              #   in Loop: Header=BB40_132 Depth=1
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:ei <- $rdx
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:state <- $rax
        .loc    9 2249 19 is_stmt 1     # source/library/bignum.c:2249:19
        cmpq    $1, %rax
        .loc    9 2249 24 is_stmt 0     # source/library/bignum.c:2249:24
        jne     .LBB40_139
.Ltmp2538:
# %bb.137:                              #   in Loop: Header=BB40_132 Depth=1
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:ei <- $rdx
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:state <- $rax
        testq   %rdx, %rdx
        jne     .LBB40_139
.Ltmp2539:
# %bb.138:                              #   in Loop: Header=BB40_132 Depth=1
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:ei <- $rdx
        #DEBUG_VALUE: mbedtls_mpi_exp_mod:state <- $rax
        .loc    9 2254 13 is_stmt 1     # source/library/bignum.c:2254:13
        movq    %rdi, %rsi
        movq    %r12, %rdx
.Ltmp2540:
        movq    %rbx, %rcx
        leaq    88(%rsp), %r8
        callq   mpi_montmul
```
If I'm reading this correctly, it's doing the same `(ei | state) != 0` test as the arm assembly above, and then choosing to compare `state` before `ei` regardless of the order of the comparisons in the source code.

So while this change is acceptable, it isn't particularly effective. We can take it since it's better than nothing, but the documentation needs to be toned down to avoid making false promises.

2021-04-29 22:01 UTC, gilles-peskine-arm commented on library/bignum.c
> +        if( state == 0 && ei == 0 )
I see, changing to `|` is bad — but it doesn't matter what we put in the code: popular compilers are “smart” enough to see that using `|` is an efficient way to compile this line. It's leaky, but C compilers don't understand that.

2021-07-06 13:18 UTC, daverodgman commented
As this is outside our threat model, and doesn't solve the issue for many compilers, closing this PR.

2021-07-06 13:18 UTC, closed without merging