[backport 2.16] Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared
ARMmbed/mbedtls pull request #4241
Opened 2021-03-17 18:48 UTC by stevew817

## Description
Backport for #4219

## Status
**READY**

2021-03-17 20:51 UTC, gilles-peskine-arm reviewed
Needs a changelog entry, other than that LGTM.

2021-03-30 09:07 UTC, mpg requested changes
Same remarks about the ChangeLog entry as for the original PR.

2021-04-27 16:12 UTC, ronald-cron-arm approved these changes

2021-04-27 19:05 UTC, gilles-peskine-arm approved these changes

2021-04-28 06:38 UTC, merged