Development new
ARMmbed/mbedtls pull request #4305
Opened 2021-04-06 16:19 UTC by daverodgman

## Description
Merge development (the 2.x branch) onto development_3.0.

2021-04-06 18:31 UTC, gilles-peskine-arm requested changes
I did the merge of the same commits and ended up with almost, but not exactly identical results. The differences are mistakes in conflict resolution. See https://github.com/gilles-peskine-arm/mbedtls/tree/development_3.0-merge-20200306 and my comments here.

In merge commits with conflicts, please document how you resolved the conflicts. See https://github.com/gilles-peskine-arm/mbedtls/tree/development_3.0-merge-20200306 for an example of what I consider adequate documentation.

However, checking the base of the merge, I think you picked the wrong commit. The first parent is itself a merge of `development` into an earlier version of `development_3.0`. This merge has several conflicts which I have not reviewed and which are not explained in the commit message. Furthermore the commit from `development` (01a622a1a4c16ec99ed82961be91417d7f86ee42) is 3 weeks old.

I'm ok with incremental merges (so ok to start with 01a622a1a4c16ec99ed82961be91417d7f86ee42), but I don't see any advantage to making the merges incremental on _both_ sides and doing back-and-forth on the 3.0 side. Please make a merge of `development` (or some ancestor of it) directly into `development_3.0`.

2021-04-06 18:31 UTC, gilles-peskine-arm commented on visualc/VS2010/mbedTLS.vcxproj
> +    <ClCompile Include="..\..\tests\src\asn1_helpers.c" />
This is a generated file. Instead of resolving the conflict manually, run `scripts/generate_visualc_files.pl`.

2021-04-06 18:31 UTC, gilles-peskine-arm commented on programs/ssl/ssl_test_lib.h
> +#include "test/certs.h"
Incorrect conflict resolution. `test/certs.h` is already present a few lines further down. It should have been removed in the merge commit, consistent with the history of the branches: removal of `library/certs.h` in 3 and addition of `hmac_drbg.h` in 2.

2021-04-06 19:19 UTC, daverodgman commented
Thanks Gilles, seems that it was indeed accidentally based on the wrong commit. I've updated it accordingly. I haven't documented the conflict resolution (yet) as your link above is broken.

2021-04-06 19:31 UTC, gilles-peskine-arm commented
Sorry, I used the wrong branch name in the link to my merge. I've edited my message above.

2021-04-07 12:31 UTC, gilles-peskine-arm requested changes
I did the merge. This time I'm happy that this is a merge of the head of [`development`](https://github.com/ARMmbed/mbedtls/tree/development) into the head of [`development_3.0`](https://github.com/ARMmbed/mbedtls/tree/development_3.0).

I [did the merge myself](https://github.com/gilles-peskine-arm/mbedtls/tree/development_3.0-merge_2.x-20200306). Differences:

* Whitespace differences in changelog entries and in `psa_crypto_rsa.c`. Can go either way.
* Incorrect conflict resolution on your side in `programs/test/cpp_dummy_build.cpp`. All headers from `include/mbedtls` must be listed, even `config_psa.h`. This is enforced by `all.sh build_default_make_gcc_and_cxx`, but due to a [known bug](https://github.com/ARMmbed/mbedtls/issues/2570) the CI ignores the failure (it's still present in the logs, but you have to know what to look for).

Regarding completeness, there's the MPS enum names issue that `check-names.sh` pointed out, and other than that I can't think of anything missing.

2021-04-07 12:50 UTC, daverodgman commented
I've fixed the missing include in cpp_dummy_build (although I can't find any previous mention of this include in the git history, so unclear if this is a merge conflict or something that was missed). If it was missed, possibly it would be better as a separate commit - but I don't think it really matters.

This should address everything except the MPS enum naming issue - I'm looking at this in #4306

2021-04-07 12:55 UTC, gilles-peskine-arm commented
`config_psa.h` was added to `cpp_dummy_build.cpp` in the `development` branch in #4159. There was a conflict in the merge here with the adjacent removal of `certs.h`. The correct resolution of that conflict was to keep `config_psa.h` added in 2.x and not re-add `certs.h` removed in 3.0.

2021-04-08 14:13 UTC, gilles-peskine-arm approved these changes
This is a correct merge of [`development`](https://github.com/ARMmbed/mbedtls/tree/development) at 38ff9adacb49d8352511c477a37d09dffbad67fb and [`development_3.0`](https://github.com/ARMmbed/mbedtls/tree/development_3.0) at 6741fc914851de968c9dfa5a690d1183b650b144.

I did the merge myself slightly differently, first taking `development` at b42025977706261ac51442f90a0a0c72a852b9a8 and `development_3.0` at e6a778286fc50b05b477624cbac1c3ea23c01de7 (as in an earlier iteration of this PR), then updating with #4306 cherry-picked and a merge of `development`. I ended up with https://github.com/ARMmbed/gilles-peskine-arm/tree/development_3.0-merge_2.x-20200306 which is identical except for cosmetic differences.

2021-04-08 14:42 UTC, ronald-cron-arm approved these changes
I've done on my side the merge of 6741fc9 from the development branch into 38ff9ad which is the current head of development_3.0 and ended-up with the same tree as the ante-penultimate commit (73e3e2c) in this PR. The two last commits look good to me thus approving.

2021-04-08 14:45 UTC, merged