Backport 2.16: Test read of zero-padded negative number
ARMmbed/mbedtls pull request #4322
Opened 2021-04-09 15:12 UTC by gilles-peskine-arm

This is a partial backport of https://github.com/ARMmbed/mbedtls/pull/4297.

* Backport the added unit tests for `mbedtls_mpi_read_string`.
* This revealed that `"-0"` is parsed as a negative 0, which is not handled correctly everywhere. (`mbedtls_mpi_cmp_mpi` does say that +0 and -0 are equal, but `mbedtls_mpi_lt_mpi_ct` doesn't.) So backport the change to `mbedtls_mpi_read_string` as well, even if it's only for the sake of this edge case (the original motivation for this change, which is that negative numbers with a leading zero were parsed incorrectly, does not apply to 2.16.).
* Backport the added unit tests for `mbedtls_ecp_muladd`.
* Do not backport the bug fix to `fix_negative` since it was only briefly broken in `development.
* Do not backport the unit tests for `fix_negative` because it's an internal function and it's too much work to expose it in 2.16 (doable, but I don't think it's worth the effort).

2021-04-13 08:05 UTC, mpg requested changes
Looks almost entirely good to me.

I agree with the PR description about what's relevant to backport here and what's not relevant or not worth it. I checked that each commit here is a proper backport of a corresponding commit in #4297 or #4323.

The only thing is that one test description is wrong, and apparently the commit that fixed it in the original PR was not cherry-picked here.

2021-04-13 08:05 UTC, mpg commented on tests/suites/test_suite_mpi.data
> +Base test mpi_read_write_string #3 (Negative decimal -> hex)
That should be hex -> decimal

2021-04-13 09:57 UTC, mpg approved these changes
Thanks for fixing the typo. Looks all good to me now.

2021-04-15 11:59 UTC, chris-jones-arm approved these changes
I agree with the scope of the backport and I have verified that it is faithful to the original.

2021-04-15 12:00 UTC, merged