Fix unchecked return value in bignum
ARMmbed/mbedtls pull request #4380
Opened 2021-04-20 18:02 UTC by paul-elliott-arm

## Description

Fix an unchecked return valueiin bignum.c - issue found by coverity

## Status
**READY**

## Requires Backporting
Yes
2.16

## Migrations

NO

## Todos
- [ ] Tests
- [ ] Changelog updated
- [ ] Backported

2021-04-20 19:01 UTC, gilles-peskine-arm requested changes

2021-04-20 19:01 UTC, gilles-peskine-arm commented on library/bignum.c
> +        return mbedtls_mpi_lset( X, 0 );
Style:
```suggestion
        return( mbedtls_mpi_lset( X, 0 ) );
```

2021-04-20 21:01 UTC, gilles-peskine-arm approved these changes
LGTM

2021-04-22 11:08 UTC, ronald-cron-arm approved these changes

2021-04-22 11:08 UTC, merged