Disable debugging features in baremetal
ARMmbed/mbedtls pull request #4428
Opened 2021-04-27 09:48 UTC by gilles-peskine-arm

The baremetal configuration is, among other things, our default reference point for code size measurements. So disable debugging features that would not be enabled in production where code size is limited. In particular, this shrinks the core SSL modules by about half. Keep debugging features that are solely in their own modules (MBEDTLS_ERROR_C, MBEDTLS_VERSION_FEATURES) since it's easy to filter them out.

Named configurations are not documented interfaces, so we don't announce this in the changelog and we do it in LTS branches as well.

Backports:
* 2.16: https://github.com/ARMmbed/mbedtls/pull/4359
* 2.x: https://github.com/ARMmbed/mbedtls/pull/4358

2021-04-27 14:43 UTC, ronald-cron-arm approved these changes

2021-05-07 11:14 UTC, mpg commented
I'm not sure I agree with the concept behind this PR, and the reason is right there in the description: "among other things". It seems to me that one of the purposes that config is also to ensure that everything builds with embedded toolchains. From that perspective, if we remove `DEBUG_C` we'll miss potential warnings related to debug message (including all the format warnings added recently), and some of them might be platform-dependent.

Perhaps it would be better to keep `config.py baremetal` as it is, and just add a separate all.sh component for size measurement that manually disables `DEBUG_C` and `TEST_HOOKS`?

I'm not full-on objecting to the approach taken here, but I'd like to hear your counter-points to this concern.

2021-05-07 11:42 UTC, gilles-peskine-arm commented
@mpg You make a good point about platform coverage. That's a big part of why we use `config.py baremetal`. Maybe we should have both `baremetal_with_debug` and `baremetal_without_debug`? Which one (if any) gets the name `baremetal`? I'm inclined to say that “bare-metal” is what you would actually use on a baremetal platform, so no debug, and we have an extra “bare-metal plus debug” that you would use for additional validation in a testing environment.

2021-08-12 12:21 UTC, yanesca commented
> Maybe we should have both baremetal_with_debug and baremetal_without_debug?

I think that would be the right thing to do here (and I feel like the without debug variant should get the "baremetal" name. @mpg what do you think?

2021-08-13 07:38 UTC, mpg commented
If we add presets, I think none of them should be called just `baremetal` because IMO this creates too much ambiguity, especially considering we have a branch called `baremetal`, which has a config called `baremetal.h` which is entirely different.

So perhaps `baremetal_full` or even `full_baremetal` for what's currently `baremetal` (to make it clear that it's not a config you'd actually want to use on an actual device as it has way too many things enabled), and `baremetal_no_hooks` or even `full_baremetal_no_hooks` for the same thing minus `DEBUG_C`, `TEST_HOOKS`, and the perhaps upcoming [instrumentation](https://github.com/ARMmbed/mbedtls/pull/4816)?

Actually, I'm not even sure we should keep the name `baremetal` at all, how about `full_no_os`? (And `full_no_os_no_hooks`.)

Anyway, I don't want to spend too much time arguing about naming, we already have the descriptions in `config.py --help` to clarify, so any name that's not actively misleading is probably good enough as long as the help message is clear enough.

2021-08-13 07:46 UTC, mpg requested changes
As it stands, this PR reduces test coverage by not building some parts of the library with some toolchains. I think this should be fixed by either:

- keeping `config.py baremetal` as is it and explicitly calling `config.py unset MBEDTLS_DEBUG_C` and `config.py unset `MBEDTLS_TEST_HOOKS` in the few `all.sh` components where we care about size; or
- adding an appropriate new preset to `config.py` and using it in `all.sh` when appropriate, as long as the current preset (under the same or a different name) remains used when we want to test that everything builds.

If we go with the second option, despite expressing some opinions about naming I don't feel too strongly about that, so I'm prepared to approve this PR regardless of whether my preferred names were chosen, as long as testing coverage is preserved.

2021-09-01 18:10 UTC, gilles-peskine-arm commented
You make good points and I've changed my approach, to the point that it's a whole new patch.

I'm now keeping `baremetal` as it is and creating a new configuration `baremetal_size` which gives more useful code size measurements. I've kept the `baremetal` name partly because I think it's perfectly meaningful (it has more title to the name than the `baremetal` branch which is more of a `code_size_optimization` branch) and because this minimizes the change.

This PR is superseded by https://github.com/ARMmbed/mbedtls/pull/4907.

2021-09-01 18:10 UTC, closed without merging

2021-09-01 18:10 UTC, gilles-peskine-arm commented
What do we do about 2.16? Do we revert https://github.com/ARMmbed/mbedtls/pull/4359?

2021-09-02 07:07 UTC, yanesca commented
> What do we do about 2.16? Do we revert #4359?

Ideally the backport of  #4907 would revert it or work incrementally on the top of it, whichever is more convenient.

2021-09-02 08:27 UTC, gilles-peskine-arm commented
Given that 2.16 is near EOL and we aren't going to do any code size improvements on it, nor many bug fixes anymore, I was thinking of just not backporting #4907.

2021-09-02 08:35 UTC, mpg commented
Unless I'm mistaken #4395 introduced a testing regression (if we made changes to the debug code that would cause it to no longer compile on v6-M for example if would no longer be detected), so I think that needs to be addressed. Considering 2.16 is nearing EOL, I think we should go with the simplest possible fix, which IMO would be to revert 4396 and not backport 4907 - but whoever does the work should choose whatever's most convenient for them.