Remove rsa mode params
ARMmbed/mbedtls pull request #4488
Opened 2021-05-12 09:41 UTC by tom-daubney-arm

## Description
This PR addresses a partial fix for #4278. In this PR only the decrypt functions have been addressed. Relevant function calls and tests have been modified and removed to facilitate this change. Where necessary the code pathways inside functions have been removed and modified to remove functionality that is associated with using the wrong mode. In this case the wrong mode is to be using is MBEDTLS_RSA_PUBLIC with decryption functions.

## Status
**READY**

## Requires Backporting

NO  

## Migrations
If there is any API change, what's the incentive and logic for it.

YES

Removed the mode parameter from the RSA decrypt functions since using the wrong mode (MBEDTLS_RSA_PUBLIC for decrypt) is no longer supported.

2021-05-14 18:31 UTC, davidhorstmann-arm requested changes
One little thing (in a few places), otherwise looks good.

2021-05-17 08:19 UTC, tom-daubney-arm commented on include/mbedtls/rsa.h
>   *                 return #MBEDTLS_ERR_PLATFORM_FEATURE_UNSUPPORTED.
Thanks for catching that. Will fix!

2021-05-17 11:45 UTC, gilles-peskine-arm approved these changes
I have reviewed for correctness and this looks good to me.

In terms of completeness, it's difficult to say since this PR only does part of the task, but I think the only thing missing is documentation (changelog entry and migration guide entry). It's easier to write this documentation directly for the whole task, so I'm ok with merging the partial work here and having documentation in the next PR.

I think doing separate functions in separate PR makes it harder to review and not easier to do (you can make separate commits even if it's in the same PR), so I'd prefer if #4515 did everything else and not just one more small batch.

2021-05-17 11:47 UTC, davidhorstmann-arm approved these changes
LGTM - thanks!

2021-05-17 11:49 UTC, merged

2021-05-17 12:28 UTC, ronald-cron-arm commented
> 
> I think doing separate functions in separate PR makes it harder to review and not easier to do (you can make separate commits even if it's in the same PR), so I'd prefer if #4515 did everything else and not just one more small batch.

I think you are right here Gilles. With Tom we decided to go with just a partial and as small as possible first PR as it was Tom's first PR. Now that we are quite confident that what is done and how it is done is ok I agree that it would be better for the next PR to finish the work (and not two as currently planned). @tom-daubney-arm ok with that ?