build with gcc11 (2.x)
ARMmbed/mbedtls pull request #4493
Opened 2021-05-12 15:15 UTC by scareything

2021-05-12 21:39 UTC, gilles-peskine-arm requested changes
This is a faithful backport of https://github.com/ARMmbed/mbedtls/pull/4462 at this time. Like it, there are two remaining warnings with GCC 11.1 in the default configuration.

For the [`-Wstringop-overflow` warning in `ssl_tls.c`](https://github.com/ARMmbed/mbedtls/issues/4130), I don't know of a good fix that neither requires an API change in the SHA-512 module nor using a needlessly large buffer in the TLS code to use SHA-384. Ideas welcome.

2021-05-12 22:06 UTC, gilles-peskine-arm commented
For the `-Wstringop-overflow`, how about https://github.com/gilles-peskine-arm/mbedtls/tree/ssl-sha384-stringop-overflow-warning? Feel free to cherry-pick my commit.

2021-05-13 14:29 UTC, scareything commented
Thanks for the feedback and suggestions, @gilles-peskine-arm !

2021-05-19 20:03 UTC, gilles-peskine-arm approved these changes
I have verified that the changes are non-harmful and that this fixes the build with GCC 11.1 in the default config and the full config.

2021-05-20 09:37 UTC, paul-elliott-arm approved these changes
LGTM

2021-05-20 13:54 UTC, merged