Change sha256 and sha512 output type from an array to a pointer
ARMmbed/mbedtls pull request #4506
Opened 2021-05-12 22:44 UTC by gilles-peskine-arm

This is the critical part of https://github.com/ARMmbed/mbedtls/issues/4452, fixing https://github.com/ARMmbed/mbedtls/issues/4130 in a clean way.

The SHA512 part is important because the array parameter broke our build with GCC-11. The SHA256 part is less important because SHA-224 is very rarely used and the extra cost is 4 extra bytes, but it could hurt with code that systematically calculates each hash into a tight-sized buffer.

I had a quick look at other functions with array parameters and I didn't spot others where the array size is not always correct. While I think that it is best to avoid array parameters, there would not be much benefit in changing the existing APIs, so I don't think it's worth expending the limited time we have for 3.0 on that.

2021-05-18 16:20 UTC, davidhorstmann-arm requested changes

2021-05-18 16:20 UTC, davidhorstmann-arm commented on include/mbedtls/sha256.h
> + *                 for SHA-256, 28 bytes for SHA-224.
Looking at other parameters, should there be a `\c` before `28 bytes` here?
(Also in other files)

2021-05-19 10:05 UTC, davidhorstmann-arm approved these changes
LGTM.

2021-05-19 10:37 UTC, ronald-cron-arm approved these changes

2021-05-19 10:37 UTC, merged