Expose flag for critical extensions
ARMmbed/mbedtls pull request #4568
Opened 2021-05-26 14:15 UTC by creiter32

## Description

Changes the API to enable creating X.509 CSRs with critical extensions. Fixes https://github.com/ARMmbed/mbedtls/issues/4055

## Status
**READY**

## Requires Backporting
NO

## Additional comments

I didn't find any test cases for `mbedtls_x509write_csr_set_extension` so I'm not sure if this is needed.

2021-05-26 20:46 UTC, gilles-peskine-arm commented
Thank you for your contribution! This feature makes sense to me, and the code is ok.

This is an API change: any code currently using `mbedtls_x509write_csr_set_extension` will no longer compile. We don't do API changes in Mbed TLS except when there's a major version change. Fortunately, we're getting ready to go from Mbed TLS 2.x to Mbed TLS 3.0, so if this can be merged in the next couple of weeks, the API change is ok.

A changelog entry and a migration guide entry are required. See [`ChangeLog.d/00README.md`](https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog.d/00README.md) and [`docs/3.0-migration-guide.md`](https://github.com/ARMmbed/mbedtls/blob/development/docs/3.0-migration-guide.md).

It would be better to have tests, but given the preexisting lack of tests for `mbedtls_x509write_csr_set_extension` I won't insist on it. A contribution of unit tests for CSR creation with both critical and non-critical extensions would be appreciated though.

2021-05-27 08:29 UTC, creiter32 commented
@gilles-peskine-arm I have added the changelog and migration guide parts.

2021-05-27 12:07 UTC, gilles-peskine-arm requested changes
Looks good to me except some minor English improvements in the documentation.

I've filed the lack of tests in https://github.com/ARMmbed/mbedtls/issues/4577. Since it's preexisting, it doesn't block this pull request.

2021-05-27 12:07 UTC, gilles-peskine-arm commented on docs/3.0-migration-guide.d/csr-add-critical-extension.md
> +This does affect users who use the `mbedtls_x509write_csr_set_extension`
```suggestion
This affects applications that call the `mbedtls_x509write_csr_set_extension`
```

2021-05-27 12:07 UTC, gilles-peskine-arm commented on ChangeLog.d/issue4055.txt
> +     an extension as critical. Fixes #4055.
```suggestion
   * The function mbedtls_x509write_csr_set_extension() has an extra parameter
     which allows marking an extension as critical. Fixes #4055.
```

2021-05-27 12:07 UTC, gilles-peskine-arm commented on include/mbedtls/x509_csr.h
> + * \param critical  set to 1 to mark the extension as critical
```suggestion
 * \param critical  Set to 1 to mark the extension as critical, 0 otherwise.
```

2021-05-27 15:26 UTC, gilles-peskine-arm approved these changes
Thanks for the changes, looks good to me!

The next step in the process is a review by another maintainer. If the second reviewer requests changes, please make them in separate commits, not by amending the current commit. For future reference, making successive commits is the general rule: amending commits should be exceptional.

2021-05-28 20:17 UTC, d3zd3z approved these changes
I agree with @gilles-peskine-arm review, the code looks fine, testing would be nice, but since we don't have any surrounding testing is probably too much to ask for here, and yes, let's try to get the API change in while that can be done.

2021-05-31 10:46 UTC, merged