Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined
ARMmbed/mbedtls pull request #4586
Opened 2021-05-31 09:28 UTC by Kazuyuki-Kimura

## Description
Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined.
Fixes issue #2020

## Status
READY

## Requires Backporting
Yes
Which branch?
2.16

## Migrations
NO

## Additional comments
mbedtls_mpi_self_test() passed without problems.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

2021-06-16 08:52 UTC, mpg commented
Hi @Kazuyuki-Kimura and thanks for your contribution! Were you able to reproduce the bug and verify your fix on the affected platform?

2021-06-18 10:39 UTC, Kazuyuki-Kimura commented
Without knowing about this bug, I installed mbedTLS in a mail client I was making, and it stopped just like #2020, so I think I was able to reproduce it.
When I wrote a new assembler code to improve the speed and pass the test, I compared the results and found that the only difference was the order in which the 64-bit data was imported from memory.
microblaze allows you to choose the endianness when you embed it in your FPGA.
When we first released it, I think we created the code to work with big-endian cores.
We have passed all the necessary tests and confirmed that we can send emails to the SMTPS server without any problems.

2021-06-18 10:46 UTC, mpg commented
Thanks ! Since we don't have the relevant hardware for testing ourselves, it's important to know that your patch was tested.

2021-06-18 10:46 UTC, mpg requested changes
The patch looks good to me, just one nit-pick: could you rebase on top of current development in order to avoid the merge commits? Thanks!

2021-06-18 16:52 UTC, closed without merging