Backport 2.16: Curve and hash selection for X.509 and TLS
ARMmbed/mbedtls pull request #4622
Opened 2021-06-07 19:36 UTC by gilles-peskine-arm

This is a partial backport of #4604, a subset of #4621: only documentation updates for the LTS branch.

* Documentation clarifications in some places that I noticed while updating the documentation for curve and hash selection in #4604.

The fix for https://github.com/ARMmbed/mbedtls/issues/4608 will be backported separately.

2021-06-21 07:46 UTC, mpg requested changes
Looks good except one place where 2.16 differs from 3.0 so the documentation needs adapting.

2021-06-21 07:46 UTC, mpg commented on include/mbedtls/ssl.h
> + *                 (Default: all SHA2 hashes, largest first.)
I don't think that correct, in 2.16 `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE` is enabled in the default `config.h`.

2021-06-21 07:47 UTC, mpg commented on include/mbedtls/ssl.h
> + *                 (Default: all SHA2 hashes, largest first.)
Note: "all available hashes except MD5" was a bit misleading too, as we don't include RIPEMD-160...

2021-06-21 08:29 UTC, mpg approved these changes

2021-06-22 08:49 UTC, ronald-cron-arm approved these changes

2021-06-22 10:08 UTC, merged