Enable Curve448 support via the PSA API
ARMmbed/mbedtls pull request #4626
Opened 2021-06-08 12:48 UTC by silabs-ArchanaM

## Description
Enabled Curve448 support via the PSA API fixing #4249.
Added missing support for validating Curve448 keys fixing #3399. 

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated

2021-07-12 12:04 UTC, TRodziewicz requested changes
I think having a changelog file would be good here.

2021-07-12 12:42 UTC, ronald-cron-arm requested changes
That looks almost good to me, thanks. I have only minor comments. I would also suggest to add a "PSA generate key: ECC, Curve448, good" test similar to the "PSA generate key: ECC, Curve25519, good" one to complete the alignment of curve 25519 and curve 448 testing in test_sute_psa_crypto. Otherwise, the PR needs rebasing now.

2021-07-12 12:42 UTC, ronald-cron-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA import/export EC curve448 key pair: good (already properly masked)
```suggestion
PSA import/export EC curve448 key pair: good (already properly masked, key from RFC 7748 6.2 Alice)
```
To know where the private key comes from.

2021-07-12 12:42 UTC, ronald-cron-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA import/export EC curve448 key pair: unmasked input (check export-import-export yields properly masked output)
```suggestion
PSA import/export EC curve448 key pair: unmasked input (check export-import-export yields properly masked output, key from RFC 7748 6.2 Alice)
```

2021-07-12 12:42 UTC, ronald-cron-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA import/export-public EC curve448: accept masked input
```suggestion
PSA import/export-public EC curve448: accept masked input (key from RFC 7748 6.2 Alice)
```

2021-07-12 12:42 UTC, ronald-cron-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA import/export-public EC curve448: accept unmasked input
```suggestion
PSA import/export-public EC curve448: accept unmasked input (key from RFC 7748 6.2 Alice)
```

2021-07-12 12:42 UTC, ronald-cron-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA import/export curve448 Public Key: good
```suggestion
PSA import/export curve448 Public Key: good (key from RFC 7748 6.2 Alice)
```

2021-07-12 12:47 UTC, silabs-ArchanaM commented on library/ecp.c
> +        }
The default return value is already ret = MBEDTLS_ERR_ECP_FEATURE_UNAVAILABLE

2021-07-12 16:23 UTC, ronald-cron-arm requested changes
Thanks for addressing my comments so quickly. There are a few things that we use to do differently though:
1) when a PR is in review and it has some conflicts with the branch it is targeted to we prefer to rebase the PR rather than merge the targeted branch (development in the case of this PR). Thus, could you please remove the last merge commit and rather rebase the PR commits on top of the `development` branch. Feel free to ask if you have some doubt on how to do that.
2) concerning review conversation we let the reviewer not the PR author resolve the conversations. The PR author usually just uses the rocket icon to indicate to the reviewer that a comment has been addressed.
3) when you create new commits to address review comments please make commit message that explain what the commit does and group in one commit similar changes. For example, here a possibility is to have one commit to address the style issues with a commit message like "Fix coding style issue" (it would a squash of your three "Update library/ecp.c" commits. Then we could have one commit "test: psa: Improve the description of some curve 448 tests" ...

2021-07-13 10:17 UTC, silabs-ArchanaM commented on library/ecp.c
> +        }
The default return value is already ret = MBEDTLS_ERR_ECP_FEATURE_UNAVAILABLE

2021-07-13 16:06 UTC, ronald-cron-arm requested changes
Thanks for the changes. Almost good to me, please my last comments below.

2021-07-15 12:01 UTC, ronald-cron-arm reviewed
Thanks for the changes. You have some trailing spaces in the change log and the CI is not happy. Otherwise LGTM.

2021-07-15 13:31 UTC, ronald-cron-arm approved these changes
LGTM, thanks.

2021-07-16 08:27 UTC, TRodziewicz approved these changes

2021-07-20 19:37 UTC, gilles-peskine-arm commented on ChangeLog.d/psa_curve448_key_support.txt
> +   * Enable support for Curve448 via the PSA API, thereby fixing #4249 and
A while back we changed our policy to not acknowledge contributors in the changelog anymore. The acknowledgement policy dated back from when the change history was private. Now contributors are acknowledged via the public Git history.

Not a blocker, but please don't feel slighted if we remove this when we edit the changelog for the next release.

2021-07-20 19:37 UTC, merged