Add missing free context in at the end of aes_crypt_xts_size()
ARMmbed/mbedtls pull request #4676
Opened 2021-06-17 14:51 UTC by JoeSubbiani

## Description
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.

This Closes #4176

## Status
**READY**

## Requires Backporting
Yes 
[development_2.x](https://github.com/ARMmbed/mbedtls/pull/4678)
[mbedtls-2.16](https://github.com/ARMmbed/mbedtls/pull/4684)

## Migrations
If there is any API change, what's the incentive and logic for it.

NO

## Todos
- [x] Changelog
- [x] Backported: [2.x](https://github.com/ARMmbed/mbedtls/pull/4678), [mbedtls-2.16](https://github.com/ARMmbed/mbedtls/pull/4684)

## Steps to test or reproduce
test_suite_aes

2021-06-17 18:01 UTC, gilles-peskine-arm requested changes
Ok for the code change.

We don't always write changelog entries for bug fixes in the test suites, but given that this bug was externally reported, I think we should. Please add a file under `ChangeLog.d` with a changelog entry explaining the bug from a library user's point of view (a resource was never freed when running one particular test suite with an alternative AES implementation) and referencing the issue number — see existing changelog entries for examples.

2021-06-17 18:03 UTC, gilles-peskine-arm commented
The issue is present in 2.16 as well, so we need a second backport.

2021-06-18 17:47 UTC, daverodgman requested changes

2021-06-18 17:47 UTC, daverodgman commented on ChangeLog.d/issue4176.txt
> +     test suite with an alternative AES implementation. Fixes #4176
Missing full stop.

2021-06-18 18:09 UTC, daverodgman requested changes

2021-06-18 18:09 UTC, daverodgman commented on tests/suites/test_suite_aes.function
> +    mbedtls_aes_xts_free(&ctx);
Minor: improper spacing.

2021-06-21 15:35 UTC, gilles-peskine-arm requested changes

2021-06-21 15:35 UTC, gilles-peskine-arm commented on ChangeLog.d/issue4176.txt
> +     test suite with an alternative AES implementation. Fixes #4176.
We're rather picky on good English in changelog entries.

* “Fix an issue where X happens” → ”Fix X“ — the extra words are just a distraction.
* “resource” → “a resource”
* “where resource is never freed” has a name: it's a resource leak
* “when running one particular test suite” → “in a test suite”

```suggestion
   * Fix a resource leak in a test suite with an alternative AES
     implementation. Fixes #4176.
```

2021-06-21 16:25 UTC, gilles-peskine-arm approved these changes

2021-06-21 16:58 UTC, daverodgman approved these changes

2021-06-22 08:24 UTC, merged