Free context in at the end of aes_crypt_xts_size()
ARMmbed/mbedtls pull request #4678
Opened 2021-06-17 15:27 UTC by JoeSubbiani

## Description
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.

This is the backport for this [pull request](https://github.com/ARMmbed/mbedtls/pull/4676)

Closes #4176

## Status
**READY**

## Requires Backporting
NO 

## Migrations
NO

## Todos
- [ ] Tests

## Steps to test or reproduce
test_suite_aes

2021-06-18 09:13 UTC, daverodgman approved these changes
LGTM, thanks!

2021-06-18 09:15 UTC, daverodgman requested changes
Just saw the other PR - this should also have a Changelog entry

2021-06-18 17:45 UTC, daverodgman commented on ChangeLog.d/issue4176.txt
> +     test suite with an alternative AES implementation. Fixes #4176
Missing trailing full stop.

2021-06-18 17:46 UTC, daverodgman requested changes
Minor style comment

2021-06-18 18:07 UTC, daverodgman approved these changes
LGTM

2021-06-18 18:09 UTC, daverodgman approved these changes
LGTM

2021-06-21 09:12 UTC, paul-elliott-arm commented
CI Failure was due to failure to communicate with github. PR-Merge ran ok, and this was the only failure, so I think this is ok.

2021-06-21 16:29 UTC, gilles-peskine-arm approved these changes

2021-06-21 16:58 UTC, daverodgman approved these changes

2021-06-22 08:24 UTC, merged