Free context at the end of aes_crypt_xts_size()
ARMmbed/mbedtls pull request #4684
Opened 2021-06-18 10:12 UTC by JoeSubbiani

## Description
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.

This modification has also taken place in:
 - [development](https://github.com/ARMmbed/mbedtls/pull/4676) 
 - [2.x](https://github.com/ARMmbed/mbedtls/pull/4678)

Closes #4176

## Status
**READY**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

NO  
There is already a backport for 2.x, and the change has been made on 2.16 (here) and the development branch

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
test_suite_aes

2021-06-18 17:48 UTC, daverodgman requested changes

2021-06-18 17:48 UTC, daverodgman commented on ChangeLog.d/issue4176.txt
> +     test suite with an alternative AES implementation. Fixes #4176
Missing full stop

2021-06-21 16:29 UTC, gilles-peskine-arm approved these changes

2021-06-21 16:58 UTC, daverodgman approved these changes

2021-06-22 08:24 UTC, merged