Backport: pk.c: Ensure min hash_len in pk_hashlen_helper
ARMmbed/mbedtls pull request #4718
Opened 2021-06-23 15:24 UTC by nick-child-ibm

This is a direct backport from #4561

2021-06-23 15:45 UTC, nick-child-ibm commented
Rebased to fix typos

2021-06-29 09:37 UTC, gilles-peskine-arm requested changes
LGTM apart from the changelog entry.

2021-06-29 13:42 UTC, nick-child-ibm commented
Rebased to update changelog

2021-06-29 14:21 UTC, gilles-peskine-arm approved these changes
Thanks for the quick rework, looks good to me!

2021-06-29 14:51 UTC, TRodziewicz approved these changes
LGTM

2021-06-29 16:16 UTC, merged