Backport 2.x: Fix alert raised for invalid fragment length
ARMmbed/mbedtls pull request #4736
Opened 2021-06-28 21:06 UTC by daverodgman

Backport of the bugfix part of #4724.

2021-06-29 13:22 UTC, gilles-peskine-arm requested changes

2021-06-29 13:22 UTC, gilles-peskine-arm commented on ChangeLog.d/fix_tls_alert_codes.txt
> +   * message, as per RFC5247 section 7.2.2.
See my comments on the main PR.

2021-06-29 13:22 UTC, gilles-peskine-arm commented on ChangeLog.d/fix_tls_alert_codes.txt
> +Bugfix
What about the unsupported_ext cases?

2021-06-29 14:16 UTC, gilles-peskine-arm requested changes
Ok for the alert changes, but the error codes must not change.

2021-06-29 14:16 UTC, gilles-peskine-arm commented on include/mbedtls/ssl.h
> +#define MBEDTLS_ERR_SSL_UNSUPPORTED_EXTENSION             -0x5E00  /**< Client received an extended server hello containing an unsupported extension */
We shouldn't add a new error code in 2.x. Please change the alert only.

2021-06-29 15:17 UTC, ronald-cron-arm submitted a review, later dismissed
This PR backports the alert message changes flagged as bug fix in #4724 and only this. LGTM.

2021-06-29 15:19 UTC, hanno-arm submitted a review, later dismissed

2021-06-29 15:21 UTC, gilles-peskine-arm approved these changes

2021-06-29 19:36 UTC, gilles-peskine-arm commented on tests/ssl-opt.sh
> -            -S "None of the common ciphersuites is usable"
No, this hasn't changed in 2.x or 2.16

2021-06-29 20:59 UTC, gilles-peskine-arm approved these changes

2021-06-30 07:20 UTC, ronald-cron-arm approved these changes

2021-06-30 08:02 UTC, merged