Fix divide by zero if macro used with wrong key type
ARMmbed/mbedtls pull request #4758
Opened 2021-07-07 16:40 UTC by paul-elliott-arm

## Description
If PSA_CIPHER_ENCRYPT_OUTPUT_SIZE was called on a non symmetric key, then a divide by zero could happen, as PSA_CIPHER_BLOCK_LENGTH will return 0 for such a key, and PSA_ROUND_UP_TO_MULTIPLE will divide by theblock length.

Found by coverity (and with apologies for making an already complicated macro even more so)

## Status
**READY**

## Requires Backporting
Unsure

## Migrations
If there is any API change, what's the incentive and logic for it.
NO

## Todos
- [ ] Tests
- [ ] Backported

2021-07-07 19:57 UTC, gilles-peskine-arm requested changes
Please add a non-regression test and a changelog entry.

2021-07-07 19:57 UTC, gilles-peskine-arm commented on include/psa/crypto_sizes.h
>       0))
`PSA_CIPHER_UPDATE_OUTPUT_SIZE` has a similar issue.

2021-07-07 19:57 UTC, gilles-peskine-arm commented on include/psa/crypto_sizes.h
> +                                           == PSA_KEY_TYPE_CATEGORY_SYMMETRIC ? \
While this is correct, `PSA_BLOCK_CIPHER_BLOCK_LENGTH(key_type)` would make the correctness more obvious.

2021-07-20 12:43 UTC, TRodziewicz approved these changes
LGTM.

2021-07-30 16:53 UTC, gilles-peskine-arm approved these changes

2021-07-30 16:56 UTC, merged