Add openssl/gnutls tls1.3 feature tests.
ARMmbed/mbedtls pull request #4861
Opened 2021-08-10 08:51 UTC by yuhaoth

## Description
Add functions and test cases to make sure tls1.3 is available in openssl/gnutls.
Relative issues: #4417 

## Status
**IN DEVELOPMENT**

## Requires Backporting
NO  

## Migrations
NO

## Additional comments

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-08-10 08:54 UTC, hanno-arm commented on tests/ssl-opt.sh
> +requires_openssl_tls1_3
This should be gnutls?

2021-08-11 08:55 UTC, mpg requested changes
Looks pretty good to me, except we should use `OPENSSL_NEXT` in order for the test to be run, rather than skipped, in the CI.

2021-08-11 08:55 UTC, mpg commented on tests/ssl-opt.sh
> +        if $OPENSSL_CMD s_client -help 2>&1 | grep tls1_3 >/dev/null
Hmm, the problem with that is the currently on the CI the default OpenSSL is 1.0.2g which doesn't have support for TLS 1.3, so the corresponding tests are always going to be skipped in the CI; we should use `$OPENSSL_NEXT` instead.

Apparently, this script is not using `OPENSSL_NEXT` yet, but you should be able to add support based on what's done for `GNUTLS_NEXT`and `OPENSSL_LEGACY`: set the variables `$O_NEXT_CLI` and `$O_NEXT_SRV` where similar variables are set for legacy, then change the previous function from `requires_openssl` to `requires_openssl_next` and using that here.

2021-08-11 11:01 UTC, mpg reviewed
Looks good to me, let's for until the CI completes its run and check in the logs to confirm the test is no longer skipped.

2021-08-12 07:56 UTC, mpg approved these changes
I was able to confirm from the CI logs that both tests are now run on the CI, so it's all good!

2021-08-13 04:43 UTC, hanno-arm approved these changes
LGTM too

2021-08-13 07:15 UTC, merged