Move constant-time functions into a separate module
ARMmbed/mbedtls pull request #4866
Opened 2021-08-11 13:48 UTC by gabor-mezei-arm

## Description
Goals (to be done in the order described here, so as to facilitate review):
- Create a new library source file and add it to the build.
- For the sake of Mbed OS, the name of the new file must be sufficiently distinctive: Mbed OS's build system does not support two `.c` files with the same name in different subprojects.
- Do not expose any of the new functions publicly for now. Declare them only in a header file inside `library`.
- Rename existing functions to have a suitable name (`mbedtls_<modulename>_xxx`). The names should be unique except for functions that have exactly the same prototype and interface.
- Move existing constant-time code to the new file.
- Merge functions that have the same (or nearly the same) semantics but different interfaces.
- Unify the interfaces. For example: decide whether to output `0`/`1` or `0`/`~1`, to mask `uint8_t` or `size_t`.

Resolves #3649

## Requires Backporting
-[] 2.x

## Todos
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

2021-09-08 13:26 UTC, gilles-peskine-arm requested changes
I reviewed this PR commit by commit, but since I think f0c28803224935fe62a0153f6efd6214e88fa832 needs major rework, I've only made an architectural review for the work done in the subsequent commits. Other than the issue with `rsa_private` and the recommendation to delay moving base64 functions until after #4814 is fixed, I agree with the general idea of the changes made, I just haven't fully verified that they're correct.

2021-09-28 15:36 UTC, gabor-mezei-arm commented
The commits has been restructured and needs a clean review. To make the reviews easier the commit, which moving the code to the new file, is divided into smaller chunks such that each function has a designated commit.

2021-10-01 15:44 UTC, gilles-peskine-arm requested changes
In general, I'm happy with the scope and nature of what this PR does. All of my comments are minor and mostly relate to two aspects:

* The documentation. Some of my comments may be preexisting issues. A lot of comments have been upgraded to a semi-public interface (internal header), which puts them outside their original context and means more things need to be explicit.
* Many functions are now compiled unconditionally. To keep the code size down, we should keep compilation guards where possible. For example, in the current state, libmbedcrypto includes several functions that are only used by TLS code, but are built unconditionally. There may be more cases of that that I didn't comment on.

In terms of unifying interfaces, I think there's more to do eventually, but this pull request already does a good job, and we need to take a holistic look at the interface before we go further.

2021-10-20 18:23 UTC, gilles-peskine-arm submitted a review, later dismissed
Looks good to me. Thanks for doing all the changes!

2021-11-02 18:18 UTC, davidhorstmann-arm approved these changes
A few nits, LGTM otherwise!

2021-11-02 18:18 UTC, davidhorstmann-arm commented on include/mbedtls/constant_time.h
> + * This is equivalent to the standard memncmp function, but is likely to be
Nit "memncmp" -> "memcmp"

2021-11-02 18:18 UTC, davidhorstmann-arm commented on library/constant_time_internal.h
> + * This is equivalent to `if ( c1 == c2 ) memcpy(dst, src, len)`, but is likely
Nit: "dst" -> "dest" to match the name change below.

2021-11-02 18:20 UTC, davidhorstmann-arm requested changes
Whoops - meant to request changes above (nits). Otherwise fine, as I say.

2021-11-03 15:21 UTC, gilles-peskine-arm approved these changes

2021-11-03 15:22 UTC, gilles-peskine-arm requested changes

2021-11-03 15:22 UTC, gilles-peskine-arm commented on ChangeLog.d/constant_time_module.txt
> +Changes
I just realized: please add a “Features” entry for the new public function `mbedtls_ct_memcmp`.

2021-11-03 17:22 UTC, gilles-peskine-arm submitted a review, later dismissed

2021-11-03 17:34 UTC, gilles-peskine-arm commented on library/ssl_invasive.h
> -#endif /* MBEDTLS_SSL_INVASIVE_H */
This has revealed a mistake in `library/base64_invasive.h` on the `development` branch which causes `check_names.py` to fail on the merge. Let's merge https://github.com/ARMmbed/mbedtls/pull/5128 first, and then pr-merge should pass.

2021-11-03 17:36 UTC, gilles-peskine-arm commented
pr-merge is failing due to a latent minor bug in development which https://github.com/ARMmbed/mbedtls/pull/5128 fixes. pr-head is failing due to https://github.com/ARMmbed/mbedtls/issues/5012 which is fixed in development.

2021-11-04 17:05 UTC, davidhorstmann-arm approved these changes
LGTM - thanks!

2021-11-05 11:04 UTC, gilles-peskine-arm commented
[pr-merge passed](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-merge/job/PR-4866-merge/32/display/redirect) on https://github.com/ARMmbed/mbedtls/pull/4866/commits/77390dc8ecd07dbf83ef29f15f06d87cd7b7af02. Travis and pr-head [failed only on known issues](https://github.com/ARMmbed/mbedtls/pull/4866#issuecomment-959766258). So this PR is good to merge once the backport is ready.

2021-11-22 16:15 UTC, gilles-peskine-arm commented
The [latest run of pr-merge](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-4866-merge/38/pipeline) fails with seemingly relevant errors. Can you please investigate?

2021-11-22 17:02 UTC, davidhorstmann-arm commented
Hmm. The failure seems to be related to a usage of `mbedtls_ssl_safer_memcmp()` introduced in aa5f5c1f5d (#4952), after this PR was created (In `library/ssl_tls13_generic.c`, line 905).

2021-11-23 10:01 UTC, mpg commented
Ok, so that's a conflict (just not the kind that git can notice) so we should handle it like any other conflict and either rebase this branch on current development, or merge current development into this branch, depending on what's most convenient considering this PR's history. Labeling "needs: work" then.

2021-11-23 10:07 UTC, gilles-peskine-arm commented
Given that this PR involves moving code and renaming functions, a rebase would be very painful. So please do a merge, then separate commit(s) to resolve the bugs.

2021-11-24 11:56 UTC, davidhorstmann-arm approved these changes
LGTM - thanks!

2021-11-24 18:31 UTC, gilles-peskine-arm approved these changes

2021-11-24 18:33 UTC, merged