bugfix: if the len of iv is not 96-bit, ghash is used to compute y0.
ARMmbed/mbedtls pull request #4950
Opened 2021-09-17 08:43 UTC by openluopworld

An initialization vector IV can have any number of bits between 1 and
2^64. So it should be filled to the lower 64-bit in the last step
when computing ghash.

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-09-17 09:26 UTC, gilles-peskine-arm commented
Thanks for the fix! To confirm that we have the right to use your code, please add a signoff line to each commit message idicating that you accept the [Developer Certificate of Origin](https://github.com/ARMmbed/mbedtls/dco.txt). The “DCO” check needs to pass.

2021-09-17 16:57 UTC, davidhorstmann-arm requested changes
A couple of nits, but looks good otherwise!

2021-09-17 16:57 UTC, davidhorstmann-arm commented on library/gcm.c
> +        MBEDTLS_PUT_UINT32_BE( iv_len << 3,  work_buf, 12 );
2 small nits:
- We have a macro: `MBEDTLS_PUT_UINT64_BE()` - please use this instead as it is neater than using 2 calls to `MBEDTLS_PUT_UINT32_BE()`
- `* 8` is more readable than `<< 3`, as the intent of the code is clearer (and most compilers will replace the multiply with a shift anyway).

2021-09-20 07:27 UTC, gilles-peskine-arm commented
The CI is still failing. Please fix the issues reported by Travis. Then, if there are remaining issues on Jenkins, which unfortunately isn't publicly accessible, one of us maintainers can post the relevant logs.

2021-09-20 12:58 UTC, davidhorstmann-arm commented
I believe CI is failing because `iv_len` is a `size_t` which may be 32-bit on some platforms. Casting it to a `uint64_t` should solve this issue.

This raises the question of whether we should cast to `uint64_t` within the `MBEDTLS_PUT_UINT64` macro itself to prevent bad things happening in future.

2021-09-22 13:55 UTC, davidhorstmann-arm requested changes
One nit as well as making the CI pass (as I mentioned, probably casting `iv_len` to a `uint64_t` will solve it)

2021-09-22 13:55 UTC, davidhorstmann-arm commented on library/gcm.c
> +        MBEDTLS_PUT_UINT64_BE( iv_len * 8,  work_buf, 8 );
Nit: extra space before `work_buf`
```suggestion
        MBEDTLS_PUT_UINT64_BE( iv_len * 8, work_buf, 8 );
```

2021-09-22 15:49 UTC, openluopworld commented on library/gcm.c
> +        MBEDTLS_PUT_UINT64_BE( iv_len * 8,  work_buf, 8 );
thanks

2021-09-22 16:41 UTC, gilles-peskine-arm commented
Please remember to include a signoff line in every commit message. Otherwise we aren't allowed to use your code.

https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits and https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key may help.

2021-09-23 12:03 UTC, davidhorstmann-arm requested changes
Looks fine to me apart from the commit signoffs.

2021-10-06 08:42 UTC, AndrzejKurek approved these changes
Looks good. It would be also great to have a test case exposing the case of y0 miscalculation, but it might be also added separately, if at all.

2021-10-06 09:22 UTC, gilles-peskine-arm commented
@AndrzejKurek The incorrect case is for an IV length over 2^32, which is not practical for us to test (since our tests should be able to run on a microcontroller and it can't process 4GB in a reasonable time). We could add some separate large-data tests that don't run everywhere but that would be outside the scope here.

2021-10-06 12:37 UTC, davidhorstmann-arm approved these changes
LGTM modulo changelog etc

2021-11-04 18:23 UTC, gilles-peskine-arm commented
Can you please force-push to remove the merge commit and go back to 151ccb297766b6263cdce69f8ca0b785b5323499? A merge commit gives us extra review work and makes the history more complicated. Please don't include merge commits in a pull request unless the history has diverged and the merge is required to avoid a conflict.

2021-11-10 09:36 UTC, mpg commented
> Can you please force-push to remove the merge commit and go back to 151ccb2? 

@openluopworld This PR and its backport are ready for merge except for this, can you move this PR back to 151ccb2 in order to unblock them? Thanks!

2021-11-22 13:46 UTC, tom-cosgrove-arm commented
@mpg Following lack of response from originator, I have raised PR #5213 which is just this PR rolled back to before the merge commit, as requested

2021-11-22 14:41 UTC, gilles-peskine-arm commented
Continued in https://github.com/ARMmbed/mbedtls/pull/5213 without the spurious merge commit.

2021-11-22 14:41 UTC, closed without merging