TLS1.3: CertificateVerify:add tls13 read certificate verfify
ARMmbed/mbedtls pull request #4953
Opened 2021-09-19 12:46 UTC by yuhaoth

## Description

Add handler of client Certificate Verify and depended functions

## Status
**IN DEVELOPMENT**

2021-10-29 15:16 UTC, ronald-cron-arm submitted a review, later dismissed
Approving despite a last request for change on my side to not block anything while I am away. Thus to merge it you just need @paul-elliott-arm approval and another approval for the last change I am asking for and changes that @paul-elliott-arm may ask for.

2021-11-04 17:57 UTC, paul-elliott-arm commented on tests/ssl-opt.sh
> +            -c "Certificate verification flags clear"
I am slightly confused as to why you didn't add the value of ret to the debug statement, as we could have reached that point in error, which means this test is not entirely accurate.

2021-11-04 17:58 UTC, paul-elliott-arm requested changes
Everything else looks good, but I would like to see the return code used in the message the test is looking for.

2021-11-05 10:54 UTC, paul-elliott-arm approved these changes
LGTM

2021-11-08 08:36 UTC, ronald-cron-arm approved these changes
LGTM

2021-11-08 08:36 UTC, merged