PSA: fix salt length for PSS verification
ARMmbed/mbedtls pull request #5010
Opened 2021-10-04 20:26 UTC by gilles-peskine-arm

Fix `PSA_ALG_RSA_PSS` verification accepting an arbitrary salt length. This algorithm now accepts only the same salt length for verification that it produces when signing, as documented. The new algorithm `PSA_ALG_RSA_PSS_ANY_SALT` accepts any salt length. Fix #4946.

Algorithm encoding to be confirmed to align with the PSA specification (private link: https://github.com/ARM-software/psa-crypto-api/pull/529).

Needs backport to 2.2x before it becomes LTS.

2021-10-07 07:59 UTC, mstarzyk-mobica requested changes
Looks alright, although I did have trouble understanding certain parts, hopefully second reviewer will spot more.

2021-10-07 17:24 UTC, daverodgman submitted a review, later dismissed

2021-10-08 15:59 UTC, daverodgman approved these changes

2021-10-29 08:43 UTC, mstarzyk-mobica approved these changes

2021-10-29 14:36 UTC, merged