PSA Multipart AEAD CCM Internal implementation and tests.
ARMmbed/mbedtls pull request #5047
Opened 2021-10-07 17:24 UTC by paul-elliott-arm

## Description
This PR adds CCM to the algorithms supported by PSA multipart AEAD. It adds an internal implementation, and a suite of tests for it. 

This completes one of the tasks of #3721, however there may be follow up work with regards to Nonce sizes.

## Status
**READY**

## Requires Backporting
No. The changes to the underlying cipher API to support multipart are only on this branch. Multipart AEAD was also not backported.

## Migrations
No.

## Todos
- [ ] Tests
- [x] Changelog updated

## Steps to test

test_suite_psa_crypto should run clean, and all PSA tests should pass.

2021-10-22 11:51 UTC, mstarzyk-mobica submitted a review, later dismissed

2021-11-03 16:43 UTC, paul-elliott-arm commented
CI Fail is the previous (and now fixed) ssl issue, unrelated to this.

2021-11-30 07:35 UTC, mprse reviewed
Code changes looks good, but CI is still failing.
Will approve when CI is green.

2021-12-02 19:42 UTC, paul-elliott-arm commented
> Code changes looks good, but CI is still failing. Will approve when CI is green.

The CI failures are due to unrelated known CI issues (timeout issues in the SSL Tests) - hence the HEAD failing, but the Merge tests generally not. The only way I could potentially resolve this would be to force update the branch, as some fixes have been merged since this PR was made.

2021-12-08 16:32 UTC, gilles-peskine-arm requested changes
I'm only requesting some minor documentation changes because the issues I found are largely preexisting. I've filed https://github.com/ARMmbed/mbedtls/issues/5285, https://github.com/ARMmbed/mbedtls/issues/5286 and https://github.com/ARMmbed/mbedtls/issues/5287 as follow-ups to be done ASAP (but it's ok to release 3.1 without those follow-ups).

2021-12-08 16:32 UTC, gilles-peskine-arm commented on tests/suites/test_suite_psa_crypto.data
> +PSA Multipart Set Nonce: AES - CCM, NONCE = 6
Bad-case tests should generally convey the badness in their description. It's not blindingly obvious that `AES - CCM, NONCE = 6` is a negative test. Suggestion:
```suggestion
PSA Multipart Set Nonce: AES - CCM, NONCE = 6 (too short)
```
and `NONCE = 14 (too long)`

2021-12-09 09:43 UTC, paul-elliott-arm commented on tests/suites/test_suite_psa_crypto.data
> +aead_multipart_verify:PSA_KEY_TYPE_AES:"4189351B5CAEA375A0299E81C621BF43":PSA_ALG_CCM:"48c0906930561e0ab0ef4cd972":"40a27c1d1e23ea3dbe8056b2774861a4a201cce49f19997d19206d8c8a343951":"26d56961c035a7e4
It was a while ago, but I thought this was what I did do (although I had to split out the tag from a previous encrypt test). It is possible I made a mistake.

2021-12-09 13:00 UTC, mprse approved these changes

2021-12-09 13:47 UTC, gilles-peskine-arm approved these changes

2021-12-09 13:49 UTC, gilles-peskine-arm commented
The CI failures in pr-head are a known unrelated issue in TLS tests, now resolved. pr-merge passed. So CI is good.

2021-12-09 13:49 UTC, merged