CID update to RFC 9146
ARMmbed/mbedtls pull request #5061
Opened 2021-10-12 07:27 UTC by hannestschofenig

## Description

The DTLS 1.2 CID specification is finally close to publication and will be released as RFC 9146. This PR updates the implementation to match the RFC content.

Here is the CID RFC in the RFC Editor Queue: https://www.rfc-editor.org/authors/rfc9146.html

There are now two compile-time options in this PR, namely 
 * MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY  (for the CID draft version draft-ietf-tls-dtls-connection-id-05), and 
 * MBEDTLS_SSL_DTLS_CONNECTION_ID (for the RFC 9146 version). 
These two options can only be used mutuallly exclusive. 

## Status

**IN DEVELOPMENT**

## Requires Backporting

This PR does not require backporting. 

## Migrations

There is NO API change. 

## Additional comments

IMPORTANT: For those who used the temporary CID implementation in Mbed TLS please note that there were late changes to the specification that are backwards-compatibility-breaking. Two aspects have changed: 

* IANA assigned a different value to the CID extension. The Mbed TLS implementation so far used an experimental value. 
* The MAC computation and the additional data computation changed. 

## Todos

- [] Tests
- [x] Documentation
- [ ] Changelog updated

## Steps to test or reproduce

I have tested ssl_client2 against Californium.

2021-11-02 11:54 UTC, boaks commented on library/ssl_msg.c
> + *      = 13 + 1 + 8 + 1 = 23 bytes
missing "+ n" on both sides of the "=".
And definition n := CID-length

2021-11-03 11:41 UTC, hannestschofenig commented on library/ssl_msg.c
> +#else
I put all cases into the ssl_extract_add_data_from_record() function.

2021-11-03 16:50 UTC, hannestschofenig commented
Travis fails at a point where it should fail. For some reason, it defines MBEDTLS_SSL_DTLS_CONNECTION_ID  and MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY  at the same time. This is not allowed, which will lead to this error:

 #error "MBEDTLS_SSL_DTLS_CONNECTION_ID and MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY cannot be defined simultaneously"

2021-11-04 08:44 UTC, mpg commented
Lots of build in the CI try to enable everything for maximal coverage. I think you want to add `MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY` to the `EXCLUDE_FROM_FULL` list in `scripts/config.py`.

And since `MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY` is disabled both in the default config and in the "full" config, we'll want a dedicated component in `tests/scripts/all.sh` that builds with that option enabled and runs a few tests. I think something similar to the existing `component_test_no_renegotiation` would be good.

2021-11-18 09:57 UTC, gergelynagymate requested changes
Hi,
I suggest this bug fix might be incorrect. There should stay the #else #endif, but the epoch and sequence number should be also appended just above in an else branch (when rec->cid_len==0). 
The present solution appends the epoch and sequence number twice resulting incorrect MAC calculation:

![additional_data](https://user-images.githubusercontent.com/94604268/142392589-517e51d5-314c-4c97-909e-ebace42c2e4a.png)

Thanks for considering my feedback. 
Best regards, Gergely

2021-11-18 11:09 UTC, boaks commented
Implementing the different variants in [Eclipse/Californium](
https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/Record.java#L488-L507), I struggled and decided to split it in different function. Maybe, that's also an idea to go.

2021-11-18 11:26 UTC, boaks commented
I guess, the `#endif` in line 558, needs to be a `#else` and a `#endif` must be added between line 561 and 562.
 
[wrong `#endif`](https://github.com/ARMmbed/mbedtls/blob/3221ee21c6da4047e8629241ce706c8a2b78b0b5/library/ssl_msg.c#L558-L562)

2021-11-18 12:03 UTC, gergelynagymate commented
> 
> 
> I guess, the `#endif` in line 558, needs to be a `#else` and a `#endif` must be added between line 561 and 562.
> 
> [wrong `#endif`](https://github.com/ARMmbed/mbedtls/blob/3221ee21c6da4047e8629241ce706c8a2b78b0b5/library/ssl_msg.c#L558-L562)
> 

Yes, as it was before the commit, but the epoch and sequence should be also added when MBEDTLS_SSL_DTLS_CONNECTION_ID  is defined but rec->cid_len is 0, as the case with messages coming from the server which does not include CID. 
In this case RFC6347 and RFC7366 applies, am I correct?

    #if defined(MBEDTLS_SSL_DTLS_CONNECTION_ID)
            if (rec->cid_len != 0)
            {
                // seq_num_placeholder
                memcpy(cur, seq_num_placeholder, sizeof(seq_num_placeholder));
                cur += sizeof(seq_num_placeholder);
    
                // tls12_cid type
                *cur = rec->type;
                cur++;
    
                // cid_length
                *cur = rec->cid_len;
                cur++;
            } else {
                // epoch + sequence number
                memcpy( cur, rec->ctr, sizeof( rec->ctr ) );
                cur += sizeof( rec->ctr );
            }
    #else
          // epoch + sequence number
            memcpy( cur, rec->ctr, sizeof( rec->ctr ) );
            cur += sizeof( rec->ctr );
    #endif /* MBEDTLS_SSL_DTLS_CONNECTION_ID */

This works for me both with MBEDTLS_SSL_DTLS_CONNECTION_ID defined or not.

2021-11-18 12:29 UTC, boaks commented
I would still feel much more comfortable, if the "extract" in `ssl_extract_add_data_from_record` is split into different functions for each variant, `RFC6347`, `RFC9146` and `RFC9146 pre/deprecated`.  Using the effective cid length and NONE, CID, DEPRECATED_CID macros then in the `ssl_extract_add_data_from_record` to select the variant's function.

2022-01-17 18:44 UTC, boaks commented
Thumbs up!

[mbedtls_cd_54.pcapng.gz](https://github.com/ARMmbed/mbedtls/files/7884097/mbedtls_cd_54.pcapng.gz)

Ensure your wireshark supports the final hello extension 54, otherwise it displays many "malformed records" ;-) (version 3.7. 0).

2022-01-28 11:24 UTC, mpg requested changes
This is only a first pass, looking at the general structure, which looks pretty good so far!

I'm thinking that perhaps with a different strategy for the compat option, we could reduce the number of places where the dependency would have to change, which would be convenient for testing too.

I found a couple of minor issues, including one that's causing lots of CI failures. I didn't look if there were other sources of failures, I suggest fixing the one first and then seeing what the CI says.

I had a look, and it doesn't seem that OpenSSL or Gnu TLS support this extension, so I don't think we'll be able to add automated interop testing to our CI in the short-to-medium term. Thanks to @boaks for the manual interop testing though!

I'll make a second pass next week, more focused on correctness / security / maintainability of the actual new code, but I already appreciate that everything is isolated in a single, well-commented function, so hopefully everything should go fine!

2022-01-28 11:24 UTC, mpg commented on include/mbedtls/mbedtls_config.h
> + * published in RFC 9146 cannot be enabled at the same time.
Also, we need to add a component in `tests/scripts/all.sh` that builds with the legacy config and executes the tests (`make test` and `tests/ssl-opt.sh -f'Connection ID'` and `tests/ssl-opt.sh -f'CID').

By the way, I think existing tests in `tests/suites/test_suite_ssl.*` and `tests/ssl-op.sh` that depend on `MBEDTLS_SSL_DTLS_CONNECTION_ID` should probably now depend on that or the legacy version... which would require special treatement in `ssl-opt.sh` as it doesn't have `requires_one_of_these_enabled`.

I'm starting to wonder if the strategy for the options is right. What if we had instead:
- `MBEDTLS_SSL_DTLS_CONNECTION_ID` that controls whether _some_ version of C-ID is enabled
- `MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT` that could be set to `0` (default) for the standard version, `1` for the legacy draft version, and perhaps in the future `2` for both (negotiated at runtime) if ever implement that.

That would avoid changing all the places that currently depend on `MBEDTLS_SSL_DTLS_CONNECTION_ID`, unless I'm mistaken we'd only need to consult the value of `MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT` in `ssl_extract_add_data_from_record()` and when defining `MBEDTLS_TLS_EXT_CID`. (And would also make it easier to remove the compat option later.)

Wdyt?

2022-01-28 11:26 UTC, mpg commented on include/mbedtls/mbedtls_config.h
> + * Support for this functionality is included for backwards-
Note: we first need to revolve the discussion about what options we use, with what meaning: https://github.com/ARMmbed/mbedtls/pull/5061#discussion_r794417327

2022-01-28 11:26 UTC, mpg commented on library/ssl_misc.h
> +#if !(defined(MBEDTLS_SSL_DTLS_CONNECTION_ID) || defined(MBEDTLS_SSL_DTLS_CONNECTION_ID_LEGACY))
Note: we first need to revolve the discussion about what options we use, with what meaning: https://github.com/ARMmbed/mbedtls/pull/5061#discussion_r794417327

2022-01-28 11:38 UTC, boaks commented
> I had a look, and it doesn't seem that OpenSSL or Gnu TLS support this extension, so I don't think we'll be able to add automated interop testing to our CI in the short-to-medium term. Thanks to @boaks for the manual interop testing though!

I added that test to [Eclipse/Californium](https://github.com/eclipse/californium/tree/master/californium-tests/californium-interoperability-tests), see also issue #5443 for a minor improvement.

It's not "fully automated", I generate the c-artifacts manually "on my machine". The Californium build tests are using that to ensure, that the development of Californium itself didn't break that function.

(By the way, unfortunately too many (d)tls libraries are not that useful for IoT. I added a simple dtls cid client in the meantime to [Eclipse/TinyDtls](https://github.com/eclipse/tinydtls)  to have at least a second client implementation.)

2022-02-01 07:39 UTC, boaks commented on include/mbedtls/mbedtls_config.h
>  //#define MBEDTLS_SSL_DTLS_CONNECTION_ID
FMPOV,  as long as [DTLS-RRC](https://github.com/tlswg/dtls-rrc) isn't complete, I would recommend to add the guidance, that for systems with  "massive message exchanging and significant traffic amplification", an equivalent protection is required.
But not to stress that too much: the main use-case is for me, power saving sensor networks, which naturally have no amplification. And I also don't assume, that in the next future (before that RRC gets completed) such massive deployment will be realistic.

2022-02-28 14:32 UTC, hannestschofenig commented on include/mbedtls/mbedtls_config.h
> + * published in RFC 9146 cannot be enabled at the same time.
Regarding the option setting, I think I have to agree with you.

2022-05-13 12:15 UTC, daverodgman requested changes
Please add a Changelog

2022-06-28 16:02 UTC, boaks commented
I've tested the latest #7762c6e67151d459458e92b69c70b572168cc15e with Californium successfully.

2022-06-29 07:30 UTC, hannestschofenig commented
> FMPOV,
> 
> ```
> #if defined(MBEDTLS_SSL_DTLS_CONNECTION_ID)
>     unsigned char add_data[23 + MBEDTLS_SSL_CID_IN_LEN_MAX];
> #else
>     unsigned char add_data[13 + 1 + MBEDTLS_SSL_CID_IN_LEN_MAX ];
> #endif
> ```
> 
> must be used for both, `mbedtls_ssl_encrypt_buf` and `mbedtls_ssl_decrypt_buf`.
> 
> My tests have been successful, because I use a rather short cid.

I have changed the add_data structure to add_data[13] for the case when CIDs are not used.

```
#if defined(MBEDTLS_SSL_DTLS_CONNECTION_ID)
    unsigned char add_data[23 + MBEDTLS_SSL_CID_IN_LEN_MAX];
#else
    unsigned char add_data[13];
#endif
```

2022-07-24 15:28 UTC, boaks commented
@mpg 
@daverodgman 

FMPOV, this PR is "LGTM".

You both have requested changes, so would it be possible for you to spend some time in review the changes?
It's 2 weeks ago, that Hannes updated it towards the "development-branch". I'm afraid, it will be a endless loop, if reviews takes longer.

2022-07-24 15:33 UTC, boaks commented
@hannestschofenig 

I hope the reviews will be done soon. Afterwards I would propose, that the commits are squashed and you add the missing "Signed-off-by: Author Name <authoremail@example.com>" to the resulting commit.

Or are there any reasons, not to squash after the reviews?

2022-08-02 20:58 UTC, gilles-peskine-arm commented
@boaks What's reviewed is what we merge, including the commit history. We want the commit history to accurately reflect the development and the review, and we want it to be helpful to readers (one thing at a time), so we never squash, and we avoid rebasing during review unless there's a compelling reason (e.g. merge conflict, or commit that doesn't make sense on its own such as forgetting to add a new file).

2022-08-02 20:59 UTC, gilles-peskine-arm commented
The DCO check is failing. Please add signoff lines to all commit messages before we can (re)start reviewing.

2022-08-03 07:52 UTC, boaks commented
> What's reviewed is what we merge ...

For work, which is done over such a long period, this will hardly work. Nor do I see, that the most are interested in the history of the withdrawn stuff. At least I prefer to focus on the final outcome and the proper documentation of that.

Anyway, this is not my PR, so proceed as you prefer.

2022-09-13 21:10 UTC, plskeggs commented
@hannestschofenig -- is it safe to assume that this PR is superseded by https://github.com/Mbed-TLS/mbedtls/pull/6264?

2022-09-26 13:11 UTC, hannestschofenig commented
I created the new PR to deal with the Signed-off-by issue. The new PR also doesn't carry the entire commit history because there was a lot of "forwards-and-backwards" in the design.

2022-09-26 13:12 UTC, boaks commented
@hannestschofenig 

Thanks a lot for all the work an the big step ahead now!

2022-10-12 07:39 UTC, boaks commented
Some news:

For mbedtls there is now a renewed [PR 6264](https://github.com/Mbed-TLS/mbedtls/pull/6264).

Just for the curious ones, which want to have a first impression and collect some experience with DTLS 1.2 CID and a Thingy:91, I prepared a demo-client with [Eclipse/tinydtls](https://github.com/boaks/zephyr-coaps-client).

2022-10-18 07:59 UTC, mpg commented
Closing, superseded by https://github.com/Mbed-TLS/mbedtls/pull/6264

2022-10-18 07:59 UTC, closed without merging