Pr/add rsa pkcsv15
ARMmbed/mbedtls pull request #5202
Opened 2021-11-22 08:16 UTC by xkqian

To support RSA signature scheme PKCS#1 V1.5.

It will depend on the PR #5127

2021-11-23 13:47 UTC, ronald-cron-arm requested changes

2021-11-23 13:47 UTC, ronald-cron-arm commented on library/ssl_tls13_generic.c
> +        case MBEDTLS_TLS13_SIG_RSA_PKCS1_SHA256:
This signature algorithm in TLS 1.3 is tolerated only for signatures in Certificate and should not be used for the signature in CertificateVerify (at least it is highly recommended). MBEDTLS_TLS13_SIG_RSA_PKCS1_SHA256 is advertised in the signature algorithms extension only to state that we support it for signatures in certificates.
Thus please remove this.

2021-11-23 13:47 UTC, ronald-cron-arm commented on programs/ssl/ssl_client2.c
> +                sig_alg_list[i++] = MBEDTLS_TLS13_SIG_RSA_PKCS1_SHA1;
```suggestion
                sig_alg_list[i++] = MBEDTLS_TLS13_SIG_RSA_PKCS1_SHA256;
```

2021-11-25 08:32 UTC, ronald-cron-arm requested changes

2021-11-25 08:32 UTC, ronald-cron-arm commented on tests/ssl-opt.sh
> +requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL
From the point of view of our TLS 1.3 client it is the same test as the one before thus I think we can live without it.

2021-11-25 11:54 UTC, ronald-cron-arm approved these changes
LGTM

2021-11-26 02:07 UTC, xffbai approved these changes
Looks good to me

2021-11-26 07:07 UTC, merged