Move base64 constant-time functions to the new module
ARMmbed/mbedtls pull request #5236
Opened 2021-11-26 13:50 UTC by gabor-mezei-arm

## Description
The goal of this task is to move base64 constant-time functions to the new constant-time module.

## Requires Backporting
- [ ] 2.x

## Todos
- [x] Documentation
- [ ] Backported

2021-11-30 15:53 UTC, davidhorstmann-arm requested changes
One question, LGTM otherwise.

2021-11-30 16:39 UTC, gabor-mezei-arm commented on library/constant_time_internal.h
> +
They are called from the `base64.c`, so the function declarations must always be available. The `constant_time_invasive.h` contains only the locally used functions which needs to be tested and these are only available when testing.
The `mbedtls_ct_base64_enc_char` and `mbedtls_ct_base64_dec_value` were local functions in `base64.c` and that is why were in the `base64_invasive.h`. After moving to the constant-time module they are referenced from another module so cannot be local functions.

2021-11-30 16:42 UTC, davidhorstmann-arm approved these changes
LGTM - thanks!

2021-12-08 12:23 UTC, mpg reviewed
I understood the goal of the task differently, so I'd like this point to be resolved before I can approve this PR. https://github.com/ARMmbed/mbedtls/issues/4926

2021-12-08 14:03 UTC, mpg approved these changes
My misunderstanding about the intended scope of the task has been clarified. All looking good to me.

2021-12-09 11:40 UTC, merged