TLS1.3: Edit docs to explain not changing curve order.
ARMmbed/mbedtls pull request #5242
Opened 2021-11-29 11:14 UTC by paul-elliott-arm

Signed-off-by: Paul Elliott <paul.elliott@arm.com>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description

TLS1.3 MVP would benefit from a different curve group preference order in order to avoid a HelloRetryRequest (which are not yet handled), however, changing the curve group preference order would affect both TLS1.2 and TLS1.3, which is undesirable for something rare that can be relatively easily worked around.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [ ] Documentation

2021-11-30 09:27 UTC, daverodgman approved these changes

2021-11-30 09:27 UTC, daverodgman commented on docs/architecture/tls13-experimental.md
> +	  difficult (we have no desire to change TLS1.2 behaviour). The likelyhood
likelihood

2021-11-30 17:48 UTC, daverodgman approved these changes

2021-12-01 09:41 UTC, ronald-cron-arm requested changes

2021-12-01 09:41 UTC, ronald-cron-arm commented on docs/architecture/tls13-experimental.md
> +      preferred group. This could, however end up with connection failure if the
```suggestion
      preferred group. This could end up with connection failure if the
```

2021-12-01 09:41 UTC, ronald-cron-arm commented on docs/architecture/tls13-experimental.md
> +      `secp384r1` and finally `secp521r1`. If we could therefore fix the use of
At this point I do not think it is clear what "fix" is referring to as the actual default order has not been introduced yet.

2021-12-02 17:43 UTC, ronald-cron-arm requested changes
Just a typo, otherwise LGTM, thanks.

2021-12-02 17:43 UTC, ronald-cron-arm commented on docs/architecture/tls13-experimental.md
> +      curve `x25519`. The MVP would, hoewever, rather keep the preference order
```suggestion
      curve `x25519`. The MVP would, however, rather keep the preference order
```

2021-12-03 17:27 UTC, ronald-cron-arm approved these changes

2021-12-06 09:19 UTC, ronald-cron-arm commented
@daverodgman are you still ok with this new version ?

2021-12-07 11:00 UTC, daverodgman approved these changes

2021-12-07 11:01 UTC, merged