Forward port to 3.x: Introduce PSA test driver library to test PSA configuration
ARMmbed/mbedtls pull request #5263
Opened 2021-12-03 17:54 UTC by ronald-cron-arm

Forward port of #5089.

2021-12-06 15:31 UTC, gabor-mezei-arm requested changes

2021-12-06 15:31 UTC, gabor-mezei-arm commented on tests/include/test/drivers/crypto_config_test_driver_extension.h
> +#define MBEDTLS_PSA_ACCEL_KEY_TYPE_ARC4 1
Delete this. ARC4 support is already removed.

2021-12-07 09:08 UTC, ronald-cron-arm commented
@gabor-mezei-arm I believe I've addressed your comments, please have another look.

2021-12-07 10:51 UTC, gabor-mezei-arm approved these changes
Looks good to me

2021-12-07 11:52 UTC, merged