List ssl_debug_helpers_generated.h in generated files
ARMmbed/mbedtls pull request #5329
Opened 2021-12-13 22:22 UTC by gilles-peskine-arm

Fix intermittent failure of parallel builds from a fresh checkout, as seen recently in the `code-coverage` nightly CI job (https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2281/, https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2284/).

Not applicable to older branches.

2021-12-13 22:46 UTC, mpg approved these changes
LGTM

2021-12-13 22:49 UTC, mpg requested changes

2021-12-13 22:49 UTC, mpg commented on tests/scripts/check-generated-files.sh
> +check scripts/generate_ssl_debug_helpers.py library/ssl_debug_helpers_generated.hc library/ssl_debug_helpers_generated.c
Well, nope, the CI points out a typo: `.hc`

2021-12-14 08:16 UTC, mpg approved these changes
LGTM now

2021-12-14 08:49 UTC, yuhaoth approved these changes
LGTM.

2021-12-14 08:57 UTC, merged