Swap the client and server random for TLS 1.3 f_export_keys
ARMmbed/mbedtls pull request #5382
Opened 2022-01-04 18:03 UTC by lhuang04

Summary:
For TLS 1.3, the client random is in the [first part](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_client.c#L709-L711) of `randbytes`, while the server random is the [second part](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_client.c#L1112-L1115).
When we do the `f_export_keys`, the [order of client random and server random](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_keys.c#L1013-L1014) is not matching the definition of [mbedtls_ssl_export_keys_t](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L1207-L1208). Fix it by swapping the order.

Test Plan:
Check the log to make sure the NSS log is aligned.

# Apply the following patch to enable NSS log for TLS 1.3
```
diff --git a/programs/ssl/ssl_test_common_source.c b/programs/ssl/ssl_test_common_source.c
index 62cd35de8..4f58f6c39 100644
--- a/programs/ssl/ssl_test_common_source.c
+++ b/programs/ssl/ssl_test_common_source.c
@@ -60,8 +60,8 @@ void nss_keylog_export( void *p_expkey,
     size_t j;
 
     /* We're only interested in the TLS 1.2 master secret */
-    if( secret_type != MBEDTLS_SSL_KEY_EXPORT_TLS12_MASTER_SECRET )
-        return;
+//    if( secret_type != MBEDTLS_SSL_KEY_EXPORT_TLS12_MASTER_SECRET )
+//        return;
 
     ((void) p_expkey);
     ((void) server_random);
```

# Run client with nss key log
```
programs/ssl/ssl_client2 server_addr=::1 server_port=4433 debug_level=3 min_version=tls13 max_version=tls13 nss_keylog_file=/tmp/nss_keylog_file.test.txt nss_keylog=1  
```

# Before the fix:
```
ssl_tls13_client.c:0711: |3| dumping 'client hello, random bytes' (32 bytes)
ssl_tls13_client.c:0711: |3| 0000:  55 ec c3 6c a6 a4 5a 22 33 db 8a a1 30 33 8e f2  U..l..Z"3...03..
ssl_tls13_client.c:0711: |3| 0010:  15 bc d1 81 1b cd 22 38 8f 1f 94 f7 f9 b6 75 d7  ......"8......u.
ssl_tls13_client.c:0734: |3| dumping 'session id' (32 bytes)

ssl_tls13_client.c:1115: |3| dumping 'server hello, random bytes' (32 bytes)
ssl_tls13_client.c:1115: |3| 0000:  b4 13 62 9a eb f6 5d ec 5e ad e4 51 94 3a 93 20  ..b...].^..Q.:.
ssl_tls13_client.c:1115: |3| 0010:  64 7d 7b e6 fc b7 64 79 f2 7c 4d 4f 38 ed 83 f6  d}{...dy.|MO8...
ssl_tls13_client.c:1034: |3| dumping 'Session ID' (32 bytes)
ssl_tls13_keys.c:0965: |2| => mbedtls_ssl_tls13_generate_handshake_keys

---------------- NSS KEYLOG -----------------
CLIENT_RANDOM b413629aebf65dec5eade451943a9320647d7be6fcb76479f27c4d4f38ed83f6 8bbd3ee610cffb446eeab17631334566e2700f205c0bf803649d4f3b09550883
---------------------------------------------
```

# After the fix:

```
ssl_tls13_client.c:0711: |3| dumping 'client hello, random bytes' (32 bytes)
ssl_tls13_client.c:0711: |3| 0000:  40 5f 6c 8b b6 af 1d a3 4c cc 45 a2 68 7d f5 d7  @_l.....L.E.h}..
ssl_tls13_client.c:0711: |3| 0010:  74 ab 99 df 89 1f a0 6f 9a 34 16 f8 c6 ae 28 0f  t......o.4....(.
ssl_tls13_client.c:0734: |3| dumping 'session id' (32 bytes)

ssl_tls13_client.c:1115: |3| dumping 'server hello, random bytes' (32 bytes)
ssl_tls13_client.c:1115: |3| 0000:  b2 52 d5 62 d5 4c fc 2c 76 b6 53 f1 40 c7 91 f3  .R.b.L.,v.S.@...
ssl_tls13_client.c:1115: |3| 0010:  5e cd e0 3c fb 19 c8 65 33 b8 6c 8f 22 65 f2 64  ^..<...e3.l."e.d
ssl_tls13_client.c:1034: |3| dumping 'Session ID' (32 bytes)

---------------- NSS KEYLOG -----------------
CLIENT_RANDOM 405f6c8bb6af1da34ccc45a2687df5d774ab99df891fa06f9a3416f8c6ae280f 8b6c9dbd5704d922c439dc3602a6d96700237bb13428e65e7326e68c714271f4

```

Reviewers:

Subscribers:

Tasks:

Tags:

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2022-01-19 15:11 UTC, paul-elliott-arm reviewed
Looks good to me.

2022-01-21 15:03 UTC, lhuang04 commented
> Apologies, looks good to me, but could you please supply a changelog? (https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog.d/00README.md)

Added changelog, could you check again?

2022-01-21 16:36 UTC, paul-elliott-arm submitted a review, later dismissed
Looks good to me.

2022-01-26 15:51 UTC, ronald-cron-arm requested changes
Thanks for this contribution. Two comments on my side.

2022-01-26 15:51 UTC, ronald-cron-arm commented on library/ssl_tls13_keys.c
> +                handshake->randbytes + 32,
While at it we have a mnemonic now for the 32 here: MBEDTLS_CLIENT_HELLO_RANDOM_LEN.
Thus
```suggestion
                handshake->randbytes + MBEDTLS_CLIENT_HELLO_RANDOM_LEN,
```
would be better here I'd say.
```

2022-01-26 15:51 UTC, ronald-cron-arm commented on ChangeLog.d/tls13_f_export_keys.txt
> +   * Fix an issue that mbedtls_ssl_tls13_generate_handshake_keys calls
The change log should rather explain the consequences of the change for users than describing the bug.
Thus here something like:
"Fixed swap of client and server random bytes when exporting them alongside TLS 1.3 handshake and application traffic secret"
would be more in the spirit I think.

2022-01-27 14:04 UTC, lhuang04 commented
Updated per review comments.

2022-01-27 15:48 UTC, ronald-cron-arm approved these changes
Thanks for addressing my comments. LGTM.

2022-01-28 12:08 UTC, paul-elliott-arm approved these changes
LGTM

2022-01-28 12:09 UTC, merged