Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug
ARMmbed/mbedtls pull request #5469
Opened 2022-01-26 23:40 UTC by TautvydasZilys

## Description
Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug. This addresses https://github.com/ARMmbed/mbedtls/issues/5467.

## Status
READY

## Requires Backporting
YES

Backport to 2.28: https://github.com/ARMmbed/mbedtls/pull/5468
This was introduced in 2.27 and I don't think that's maintained anymore? So 2.28 is the furthest the backport is needed.

2022-01-28 09:19 UTC, mpg submitted a review, later dismissed
LGTM

2022-01-31 15:02 UTC, AndrzejKurek requested changes
Thanks for submitting the fix! 
Normally I would approve it, but following the discussion on the visual studio forum (and a fix already in the release process), I would suggest to change it to only affect versions before 17.1, probably `1931`, looking at https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170. Let's wait for the response about specific version number.
Great job!

2022-01-31 18:32 UTC, TautvydasZilys commented
Sounds good, I will update the PR once I know the concrete compiler version.

2022-01-31 21:43 UTC, AndrzejKurek approved these changes
LGTM. Thanks!

2022-02-01 08:20 UTC, mpg approved these changes

2022-02-01 08:21 UTC, merged