Move client_auth to handshake
ARMmbed/mbedtls pull request #5472
Opened 2022-01-28 03:12 UTC by yuhaoth

`ssl->client_auth` is used to indicate CertificateRequest received from server. If received, CertificateVerfiy and Certificate MUST be sent by client. The variable is used only in handshake stage.

- Guard it with `MBEDTLS_SSL_PROTO_TLS1_2`
- Move it to `ssl->handshake`

## Status
**READY**

2022-01-28 05:42 UTC, yuhaoth commented
ABI-API-checking fail only

2022-01-28 08:10 UTC, mpg approved these changes
LGTM, thanks for making those changes!

2022-02-02 15:36 UTC, ronald-cron-arm commented on include/mbedtls/ssl.h
> -    int MBEDTLS_PRIVATE(client_auth);                    /*!<  flag for client auth.   */
We should probably remove the comment just above (PKI layer).

2022-02-02 15:45 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +                                    from server side. If CertificateReqeust is
```suggestion
                                    from server side. If CertificateRequest has been
```

2022-02-08 08:22 UTC, ronald-cron-arm requested changes

2022-02-08 08:22 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +                                    received from server side. If CertificateReqeust
```suggestion
                                    received from server side. If CertificateRequest
```

2022-02-08 08:22 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +    int client_auth;           /*!< used to check if CertificateRequest has been
Pre-existing but while at it: this field is used as a flag thus `unsigned char` for the type is probably better.

2022-02-09 09:56 UTC, mpg approved these changes
LGTM, thanks for cleaning this up!

2022-02-09 09:57 UTC, merged