HKDF 1b: Implement Expand in TLS 1.3 based on PSA HMAC
ARMmbed/mbedtls pull request #5520
Opened 2022-02-09 16:07 UTC by gabor-mezei-arm

## Description
TLS 1.3 code (ssl_tls13_keys.c) currently uses HKDF from the legacy API, mbedtls_hkdf_. The PSA API currently only provides the full HKDF, which TLS 1.3 uses its components HKDF-Extract and HKDF-Expand separately. As a temporary measure, we'll be implementing those within TLS 1.3 based on the psa_mac_ API, which waiting for PSA to be extended.

Resolve #5402

## Todos
- [x] Tests

2022-02-14 12:20 UTC, mpg submitted a review, later dismissed
Looks good to me. Just two very minors things.

2022-02-14 12:20 UTC, mpg commented on tests/suites/test_suite_ssl.function
> +    PSA_ASSERT( psa_crypto_init() );
Minor: I would find it a bit clearer to have this at the top of the function, right after local declarations. Also, we can use `PSA_INIT( );` which improved the symmetry with `PSA_DONE( );` at the end. (Same for the other function.)

2022-02-14 12:20 UTC, mpg commented on tests/suites/test_suite_ssl.function
> +    mbedtls_free(info);
Style: spaces inside `()`. (Same for the other function.)

2022-02-16 09:02 UTC, mpg submitted a review, later dismissed
Still LGTM, thanks for the improvements.

2022-02-16 12:52 UTC, AndrzejKurek commented on library/ssl_tls13_keys.c
> +         * */
Minor formatting issue.

2022-02-16 13:03 UTC, AndrzejKurek requested changes
Please also add a test with a failing `psa_import_key`, as this code path is untested.

2022-02-18 08:04 UTC, AndrzejKurek approved these changes

2022-02-18 16:22 UTC, gilles-peskine-arm commented on tests/suites/test_suite_ssl.function
> +        psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
PSA doesn't support zero-length keys.

2022-02-18 16:50 UTC, AndrzejKurek commented on tests/suites/test_suite_ssl.function
> +        psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
That's the idea - make the key import fail.

2022-02-21 08:29 UTC, mpg approved these changes
LGTM

2022-02-21 08:30 UTC, merged