One flush output development
ARMmbed/mbedtls pull request #5523
Opened 2022-02-10 12:42 UTC by ronald-cron-arm

## Description
Fix #5499  by removing unnecessary flush of the output buffer, then expand the move of state changes from state handler sub-routines to the main handler (write states only).

## Status
IN DEVELOPMENT

## Requires Backporting
No, changes in TLS 1.3. 

## Additional comments
We are not in a position where we can trigger easily asynchronous writes on the network in TLS 1.3 testing. Thus not in a position to add easily non regression tests for the changes done by this PR. Some tests in the prototype with both the client and the server being Mbed TLS implementation do provide regression tests though.

Thus to mitigate the absence of regression tests in this PR, I have created a [companion PR] (https://github.com/hannestschofenig/mbedtls/pull/393) on the prototype branch with changes similar to the ones in this PR. We will merge it in the prototype when we merge this one in developement. The companion PR is made of four commits. If the fourth commit is removed and any of the three first kept, the test_tls13_no_mps all.sh component fails, providing some non-regression testing of the fourth commit that restricts the number of output buffer flush to one (first commit in this PR).

As we merge back regularly the development TLS 1.3 code to the prototype, the tests in the prototype will provide us non-regression testing until we are in a state of the TLS 1.3 development where those tests can be added to the development branch.

2022-02-10 13:55 UTC, ronald-cron-arm commented
One CI job failed but CI glitch.

2022-02-28 19:20 UTC, paul-elliott-arm requested changes

2022-02-28 19:20 UTC, paul-elliott-arm commented on library/ssl_tls.c
> +     * #MBEDTLS_ERR_SSL_WANT_WRITE error code.
```suggestion
     * We may have not been able to send to the peer all the handshake data
     * that were written into the output buffer by the previous handshake step, if
     * the write to the network callback returned with the
     * #MBEDTLS_ERR_SSL_WANT_WRITE error code.
```
Nitpick, but I was struggling slightly to understand this comment.

2022-03-08 14:55 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +                                         uint8_t force_flush );
I did it that way to align with the `force_flush` parameter in `mbedtls_ssl_write_record` I guess. I've changed them all.

2022-03-09 07:53 UTC, ronald-cron-arm commented
I've addressed the comments and rebased. The rebase was not straightforward due to the merge of #5471. I added new commits to move the state change from CLIENT_CERTIFICATE and CLIENT_CERTIFICATE_VERIFY states to their main handler as well.

2022-03-16 17:30 UTC, paul-elliott-arm approved these changes
LGTM

2022-03-18 09:11 UTC, xffbai approved these changes
looks good to me!

2022-03-21 07:44 UTC, merged