Tls13 and use psa crypto
ARMmbed/mbedtls pull request #5532
Opened 2022-02-11 14:23 UTC by ronald-cron-arm

## Description
Fix the incompatibility of the TLS 1.3 implementation with MBEDTLS_USE_PSA_CRYPTO.

## Status
READY

## Requires Backporting
No, TLS 1.3 only.

2022-02-14 09:23 UTC, mpg requested changes
The actual code changes look good to me, just a few minor points.

2022-02-14 15:00 UTC, ronald-cron-arm commented on docs/architecture/tls13-support.md
> +  option is an exception though, the TLS 1.3 MVP is not compatible with it.
This is the description of the MVP thus the state of the TLS 1.3 support @ 3.1.0.

2022-02-14 15:05 UTC, ronald-cron-arm commented on library/ssl_tls.c
> +    return( ( status == PSA_SUCCESS ) ? 0 : MBEDTLS_ERR_ERROR_GENERIC_ERROR );
Why not but looking at the function I do not really understand the default error code: MBEDTLS_ERR_PLATFORM_HW_ACCEL_FAILED ? Why not rather MBEDTLS_ERR_ERROR_GENERIC_ERROR ?

2022-02-14 15:06 UTC, ronald-cron-arm commented on docs/architecture/tls13-support.md
> +  | MBEDTLS_USE_PSA_CRYPTO                   | no  (3) |
I intended to have a (3) at some point but changed my mind. Fixing.

2022-02-14 17:38 UTC, gilles-peskine-arm commented on library/ssl_tls.c
> +    return( ( status == PSA_SUCCESS ) ? 0 : MBEDTLS_ERR_ERROR_GENERIC_ERROR );
For psa to mbedtls status translation, yes.

2022-02-15 08:22 UTC, ronald-cron-arm commented
@mpg thanks for the review. I believe I have addressed your comments. If the CI agrees, this should be ready for next review.

2022-02-15 08:30 UTC, mpg commented on docs/architecture/tls13-support.md
> +  option is an exception though, the TLS 1.3 MVP is not compatible with it.
Ok, but imagine I'm a user checking out Mbed TLS 3.2.0 when it's released. I'm likely more interested in the state of 1.3 support in the version I have than in some previous version. I'm not opposed to keeping some documentation about the MVP somewhere if you want to, even though I don't see the point (historians can use git), but I think quite strongly that 3.2 should come with documentation about what's support and what's not in 3.2, somewhere.

2022-02-15 08:31 UTC, mpg approved these changes
LGTM.

2022-02-15 09:49 UTC, ronald-cron-arm commented on docs/architecture/tls13-support.md
> +  option is an exception though, the TLS 1.3 MVP is not compatible with it.
I agree I was planning to indeed update this when we release 3.2.0. I prefer to keep it as the MVP definition for now to fix the errors we made in its descriptionin 3.1.0.

2022-02-15 09:52 UTC, mpg commented on docs/architecture/tls13-support.md
> +  option is an exception though, the TLS 1.3 MVP is not compatible with it.
OK, marking this discussion as resolved then.

2022-02-16 15:51 UTC, gabor-mezei-arm approved these changes
LGTM

2022-02-16 16:33 UTC, merged