TLS Cipher 2a: tickets: use PSA for protection
ARMmbed/mbedtls pull request #5614
Opened 2022-03-10 14:46 UTC by gabor-mezei-arm

## Description
In ssl_ticket.c, use psa_aead instead of mbedtls_cipher in order to protect tickets when MBEDTLS_USE_PSA_CRYPTO is enabled.

Resolve #5203

2022-03-15 09:44 UTC, superna9999 reviewed
Only spurious blank lines.

For the error handling, other SSL codes uses the following scheme:
```
        psa_status_t status = PSA_ERROR_CORRUPTION_DETECTED;

        if( ( status = psa_XXX( XXX ) ) != PSA_SUCCESS )
        {
            ret = psa_ssl_status_to_mbedtls( status );
            return( ret );
        }
```
I find it more readable, and would give coherency over the multiple SSL modules, but I don't have a strong opinion.

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
> +
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-15 09:44 UTC, superna9999 commented on library/ssl_ticket.c
```suggestion
```

2022-03-16 12:11 UTC, mpg requested changes
LGTM except for what I think is a typo, but unfortunately a significant one (variable name).

2022-03-16 12:11 UTC, mpg commented on library/ssl_ticket.c
> +    if( ( ret = psa_import_key( &attributes, k,
I think you mean `status` here.

2022-03-16 14:20 UTC, superna9999 approved these changes

2022-03-17 08:43 UTC, mpg approved these changes
Thanks for fixing the typo I noticed, and also the other typo that I had missed! Looks all good to me now.

2022-03-17 08:49 UTC, mpg commented
Regarding CI, the internal CI fully passed and the only two failures on the open CI are instances of #5583 and #5279 respectively, so they can be ignored as far as the present PR is concerned.

2022-03-17 08:50 UTC, merged